"""JSON-Schema -> Pydantic v2 source emission. Hand-rolled per Phase 17 D-01.

Coverage promise (D-02) -- translates faithfully:
  - type: "string" / "integer" / "number" / "boolean" -> str / int / float / bool
  - type: "object" with properties + required -> Pydantic BaseModel
  - type: "array" with scalar items.type -> list[<scalar>]

Degradation (D-02) -- everything else types to ``typing.Any`` with a
``# codegen: degraded -- <reason>`` comment directly above the field:
  - enum (any shape)              -> "enum not in v1.3 coverage"
  - oneOf                          -> "oneOf not in v1.3 coverage"
  - anyOf                          -> "anyOf not in v1.3 coverage"
  - $ref                           -> "$ref not in v1.3 coverage"
  - type: list (e.g. ["X","null"]) -> "multi-type / nullable not in v1.3 coverage"
  - array with non-scalar items    -> "array with non-scalar items not in v1.3 coverage"
  - unknown / missing type         -> "unknown type: <repr>"

CODEGEN-06: every emitted file starts with the AUTOGENERATED header.
D-03: `generate()` (added in Task 3) wipes generated/<slug>/ and writes fresh.

Pure-data: this module reads dicts and emits strings. No filesystem I/O in
``translate_tool``; ``generate`` (Task 3) owns ``shutil.rmtree`` + write_text.
"""
from __future__ import annotations

from dataclasses import dataclass

from jsonschema.validators import Draft202012Validator, validator_for
from mcp.types import Tool

# `Draft202012Validator` + `validator_for` are referenced here per RESEARCH
# "Don't Hand-Roll" row 1 -- MCP tool schemas declare Draft 2020-12. We deliberately
# do NOT call `check_schema` (the full metaschema validator) because it rejects
# fields like `{"type": "color"}` outright; the walker's D-02 contract is to
# DEGRADE on unknown type tokens, not refuse. `_check_schema_structural`
# below catches structurally-broken schemas (e.g. `required: "not-a-list"`)
# without forcing every type token to be a JSON Schema primitive.
_ = (Draft202012Validator, validator_for)

from mcp_test_framework.sdet._slugs import module_name, pascal_case


HEADER_TEMPLATE = (
    "# AUTOGENERATED by mcp-test-framework gen-sdet-classes -- DO NOT HAND-EDIT.\n"
    "# Source: {slug} (serverInfo.name=\"{server_name}\", version=\"{server_version}\")\n"
    "# Regenerated: {timestamp}\n"
    "# Extend by subclassing in tests/sdet/, not by editing this file.\n"
)


_SCALAR_MAP: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


@dataclass(frozen=True)
class FieldSpec:
    """A single Pydantic-model field as the walker plans it.

    py_type:        the post-`from __future__ import annotations` annotation
                    string (e.g. "str", "list[int]", "typing.Any").
    default_expr:   the right-hand side of `<name>: <py_type> = <default_expr>`.
                    For required fields this is `Field(...)`. For optional with
                    a default it is `Field(default=<repr>)`. For optional
                    without a default it is `Field(default=None)` and the type
                    becomes `<py_type> | None` (only at the top scalar level --
                    we don't degrade-then-nullable in v1.3 per D-02).
    degrade_reason: human-readable phrase if this field is a degradation,
                    else None. Emitted as `# codegen: degraded -- <reason>`
                    on the line above the field.
    default_is_none: True iff this field has no required-status AND no schema
                    default (so `_default_expr` produced `Field(default=None)`).
                    Structured signal consumed by `_format_field_line` to add
                    `| None` to the type annotation; replaces the previous
                    substring scan of `default_expr` for "default=None", which
                    false-positived on any field whose description contained the
                    literal "default=None" (reviewer issue #5).
    """
    py_type: str
    default_expr: str
    degrade_reason: str | None
    default_is_none: bool = False


class SchemaValidityError(ValueError):
    """Raised when an MCP tool's inputSchema is not a valid JSON Schema document.

    The codegen refuses to translate an invalid schema (loud-fail per CONTEXT.md
    Reusable Assets); the CLI command (Plan 17-04) maps this to an operator
    error naming the offending tool.
    """


def _check_schema_structural(tool_name: str, schema: dict) -> None:
    """Structural sanity check for a tool's inputSchema.

    Per Phase 17 RESEARCH "Don't Hand-Roll" row 1, MCP tool schemas are
    Draft 2020-12. We deliberately do NOT call
    `Draft202012Validator.check_schema(schema)` because the full metaschema
    rejects fields like `{"type":"color"}` -- and the walker's D-02 contract
    is to DEGRADE on unknown type tokens, not refuse the whole tool.

    This check catches the narrow class of malformed schemas the walker
    cannot operate on:
      - root `type:"object"` with `required` that is not a list
      - root `properties` that is not a dict (when present)

    Other shape weirdness (unknown type tokens, nested-object recursion,
    oneOf/anyOf/$ref combinators) falls through to `_emit_field` which
    degrades cleanly per D-02.
    """
    if not isinstance(schema, dict):
        return  # nothing to check; caller already coerced non-dicts away
    required = schema.get("required")
    if required is not None and not isinstance(required, list):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'required' must be a list, got "
            f"{type(required).__name__}). Refusing to translate."
        )
    props = schema.get("properties")
    if props is not None and not isinstance(props, dict):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'properties' must be an object, got "
            f"{type(props).__name__}). Refusing to translate."
        )


def _is_default_none(schema: dict, required: bool) -> bool:
    """True iff `_default_expr(schema, required)` emits `Field(default=None...)`.

    Reviewer issue #5: previously `_format_field_line` substring-matched
    `"default=None" in spec.default_expr` to decide whether to add `| None`
    to the type. That false-positived when a field's description literally
    contained the string `default=None`. This structured signal replaces it.
    """
    return (not required) and ("default" not in schema)


def _default_expr(schema: dict, required: bool) -> str:
    """Build the `Field(...)` right-hand side for a single field.

    Required fields get `Field(...)` (Ellipsis). Optional fields with a
    declared default get `Field(default=<repr>)`. Optional fields without
    a default get `Field(default=None)` -- and the type gets a `| None`
    union applied at emit-site (handled in _format_field_line) via the
    structured `FieldSpec.default_is_none` flag (NOT a substring scan --
    see `_is_default_none` and reviewer issue #5).

    description is lifted from schema["description"] if present; quoted via
    repr() for safe escaping.
    """
    desc = schema.get("description")
    desc_kwarg = f", description={desc!r}" if isinstance(desc, str) and desc else ""
    if required:
        return f"Field(...{desc_kwarg})"
    if "default" in schema:
        return f"Field(default={schema['default']!r}{desc_kwarg})"
    return f"Field(default=None{desc_kwarg})"


def _emit_field(name: str, schema: dict, *, required: bool) -> FieldSpec:
    """Translate one property's schema to a FieldSpec.

    Order of checks matters: degradation triggers (enum/oneOf/anyOf/$ref/
    multi-type) take precedence over `type:` dispatch so that
    `{"type":"string","enum":["a","b"]}` degrades to Any (not str) per D-02.

    `default_is_none` is computed ONCE here via `_is_default_none` and
    threaded through every `FieldSpec(...)` construction (reviewer issue #5:
    replaces the previous substring scan of `default_expr` for "default=None",
    which false-positived on descriptions containing that literal).
    """
    is_none = _is_default_none(schema, required)
    # Degradation triggers (D-02) -- check FIRST.
    if "enum" in schema:
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "enum not in v1.3 coverage",
            default_is_none=is_none,
        )
    for combinator in ("oneOf", "anyOf", "$ref"):
        if combinator in schema:
            return FieldSpec(
                "typing.Any", _default_expr(schema, required),
                f"{combinator} not in v1.3 coverage",
                default_is_none=is_none,
            )
    jtype = schema.get("type")
    if isinstance(jtype, list):
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "multi-type / nullable not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Faithful translation paths (D-02).
    if isinstance(jtype, str) and jtype in _SCALAR_MAP:
        return FieldSpec(
            _SCALAR_MAP[jtype], _default_expr(schema, required), None,
            default_is_none=is_none,
        )
    if jtype == "array":
        items = schema.get("items") or {}
        items_type = items.get("type")
        if isinstance(items_type, str) and items_type in _SCALAR_MAP:
            return FieldSpec(
                f"list[{_SCALAR_MAP[items_type]}]",
                _default_expr(schema, required),
                None,
                default_is_none=is_none,
            )
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "array with non-scalar items not in v1.3 coverage",
            default_is_none=is_none,
        )
    if jtype == "object":
        # Nested objects in v1.3: degrade to dict[str, Any]; full nested-model
        # emission is a v1.4 expansion. The current goal is the walker + the
        # SEAM, not deep type fidelity (D-02 narrow promise).
        return FieldSpec(
            "dict[str, typing.Any]", _default_expr(schema, required),
            None if "properties" not in schema else
            "nested-object recursion not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Unknown / missing type.
    return FieldSpec(
        "typing.Any", _default_expr(schema, required),
        f"unknown type: {jtype!r}",
        default_is_none=is_none,
    )


def _format_field_line(name: str, spec: FieldSpec, *, required: bool) -> str:
    """Render a FieldSpec to source lines (degrade comment + field decl).

    Reviewer issue #5: this used to be `"default=None" in spec.default_expr`,
    which false-positived when a description happened to contain the literal
    string "default=None". We now consult the structured
    `FieldSpec.default_is_none` flag set by `_emit_field`.
    """
    py_type = spec.py_type
    # Optional fields without an explicit default get `| None`. We add this
    # only for faithful scalar paths -- degradation already types to Any.
    if not required and spec.default_is_none and spec.degrade_reason is None and py_type != "typing.Any":
        py_type = f"{py_type} | None"
    lines: list[str] = []
    if spec.degrade_reason is not None:
        lines.append(f"    # codegen: degraded -- {spec.degrade_reason}")
    lines.append(f"    {name}: {py_type} = {spec.default_expr}")
    return "\n".join(lines)


def _emit_params_body(schema: dict | None) -> tuple[str, int]:
    """Emit the body of a <Tool>Params class. Returns (body_text, degraded_count).

    Empty / non-object inputSchema -> `pass` body. degraded_count is 0 in that case.
    """
    if not isinstance(schema, dict) or schema.get("type") != "object":
        return "    pass\n", 0
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    if not props:
        return "    pass\n", 0
    degraded = 0
    lines: list[str] = []
    # Required first (alphabetical), then optional (alphabetical) -- matches
    # `_format_param_signature` at cli.py:932-950.
    req_names = sorted(n for n in props if n in required)
    opt_names = sorted(n for n in props if n not in required)
    for name in req_names + opt_names:
        prop_schema = props[name] if isinstance(props[name], dict) else {}
        spec = _emit_field(name, prop_schema, required=(name in required))
        if spec.degrade_reason is not None:
            degraded += 1
        lines.append(_format_field_line(name, spec, required=(name in required)))
    return "\n".join(lines) + "\n", degraded


def _emit_response_body(schema: dict | None) -> tuple[str, int]:
    """Emit the body of a <Tool>Response class. D-06 stub when schema is None."""
    if schema is None:
        return "    pass\n", 0
    # When outputSchema IS declared, treat it the same as Params (object walk).
    return _emit_params_body(schema)


def translate_tool(
    tool: Tool,
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
) -> tuple[str, int]:
    """Translate one MCP Tool to a per-tool source file (str). Pure-data.

    Returns (source_text, degraded_field_count).

    Refuses to translate if `tool.inputSchema` is not a valid JSON Schema
    document (raises SchemaValidityError per "Don't Hand-Roll" row 1).
    """
    input_schema = tool.inputSchema if isinstance(tool.inputSchema, dict) else {}
    if input_schema:
        _check_schema_structural(tool.name, input_schema)

    cls_base = pascal_case(tool.name)
    header = HEADER_TEMPLATE.format(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )

    params_body, params_degraded = _emit_params_body(input_schema)
    output_schema = tool.outputSchema if isinstance(tool.outputSchema, dict) else None
    response_body, response_degraded = _emit_response_body(output_schema)

    response_class = (
        f"class {cls_base}Response(ToolResponse):\n"
        f'    """Typed response for the `{tool.name}` tool.\n\n'
        f"    Inherits .raw / .data / .text / .is_error from ToolResponse (CODEGEN-04).\n"
    )
    if output_schema is None:
        # D-06: stub class -- pass body, document the lack of outputSchema.
        response_class += (
            f"    outputSchema was undeclared at codegen time; .data falls\n"
            f"    back to JSON-parse / text-dict per CODEGEN-04 chain.\n"
            f'    """\n'
            f"{response_body}"
        )
    else:
        response_class += f'    """\n{response_body}'

    source = (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"import typing\n\n"
        f"from pydantic import BaseModel, ConfigDict, Field\n\n"
        f"from mcp_test_framework.sdet.response import ToolResponse\n\n\n"
        f"class {cls_base}Params(BaseModel):\n"
        f'    """Params for the `{tool.name}` tool.\n\n'
        f"    Generated from inputSchema. Pydantic validates required / type /\n"
        f"    default rules at construction time before the wire call.\n"
        f'    """\n'
        f"    model_config = ConfigDict(extra=\"forbid\")\n\n"
        f"{params_body}\n\n"
        f"{response_class}"
    )
    return source, params_degraded + response_degraded


# --- File emission (D-03 wipe-and-write) ----------------------------------

import datetime as _dt
import shutil
from pathlib import Path

from mcp_test_framework.sdet._slugs import server_slug


def _render_init(
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
    registry_entries: list[tuple[str, str]],  # [(tool_name, pascal_base), ...]
) -> str:
    """Render generated/<slug>/__init__.py: header + per-tool imports + _REGISTRY.

    Per RESEARCH Pattern 4 + CONTEXT.md "What gen-sdet-classes prints" (sorted).
    """
    header = HEADER_TEMPLATE.format(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )
    # Imports, sorted alphabetically by tool_name (diff-stable).
    import_lines: list[str] = []
    all_names: list[str] = []
    registry_lines: list[str] = []
    for tool_name, pascal in sorted(registry_entries, key=lambda t: t[0]):
        params_cls = f"{pascal}Params"
        response_cls = f"{pascal}Response"
        mod = module_name(tool_name)
        import_lines.append(f"from .{mod} import {params_cls}, {response_cls}")
        all_names.extend([f'"{params_cls}"', f'"{response_cls}"'])
        registry_lines.append(f'    "{tool_name}": ({params_cls}, {response_cls}),')

    all_block = "__all__ = [\n    " + ",\n    ".join(all_names) + ",\n]" if all_names else "__all__ = []"
    registry_block = (
        "# Phase 17 CODEGEN-05: tool(name) factory dispatches against this.\n"
        "# Phase 18 will consume _REGISTRY through "
        "`mcp_test_framework.sdet._tool_factory`.\n"
        "_REGISTRY: dict[str, tuple[type, type[ToolResponse]]] = {\n"
        + "\n".join(registry_lines) + "\n}\n"
    ) if registry_lines else (
        "_REGISTRY: dict[str, tuple[type, type[ToolResponse]]] = {}\n"
    )

    body = "\n".join(import_lines) + ("\n\n" if import_lines else "")
    return (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"from mcp_test_framework.sdet.response import ToolResponse\n\n"
        f"{body}"
        f"{all_block}\n\n"
        f"{registry_block}"
    )


def generate(
    *,
    server_name: str,
    server_version: str,
    tools: list[Tool],
    out_root: Path,
    timestamp: str | None = None,
) -> dict[str, int]:
    """Wipe-and-write generated/<slug>/ from a list of Tool objects.

    D-03: shutil.rmtree(target, ignore_errors=True) -> mkdir -> write per-tool
    files -> write __init__.py LAST (Pitfall 5: partial states fail clean,
    not half-imported).

    `timestamp=None` uses datetime.now(UTC) at sub-second precision; tests
    pass a fixed value for byte-identical idempotency.

    Returns counts: {"tools": <N>, "degraded_fields": <M>}.
    """
    if timestamp is None:
        timestamp = _dt.datetime.now(_dt.UTC).isoformat(timespec="seconds")

    slug = server_slug(server_name)  # raises ValueError on empty/all-non-ident
    target = out_root / slug

    # D-03 wipe.
    shutil.rmtree(target, ignore_errors=True)
    target.mkdir(parents=True, exist_ok=True)

    counts = {"tools": 0, "degraded_fields": 0}
    registry_entries: list[tuple[str, str]] = []

    # Sorted emission for diff-stability.
    for tool in sorted(tools, key=lambda t: t.name):
        rendered, degraded_n = translate_tool(
            tool, slug=slug, server_name=server_name,
            server_version=server_version, timestamp=timestamp,
        )
        per_tool_path = target / f"{module_name(tool.name)}.py"
        per_tool_path.write_text(rendered, encoding="utf-8")
        counts["tools"] += 1
        counts["degraded_fields"] += degraded_n
        registry_entries.append((tool.name, pascal_case(tool.name)))

    # Write __init__.py LAST (Pitfall 5).
    init_text = _render_init(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
        registry_entries=registry_entries,
    )
    (target / "__init__.py").write_text(init_text, encoding="utf-8")

    return counts
