"""JSON-Schema -> Pydantic v2 source emission. Hand-rolled per Phase 17 D-01.

Coverage promise (D-02) -- translates faithfully:
  - type: "string" / "integer" / "number" / "boolean" -> str / int / float / bool
  - type: "object" with properties + required -> Pydantic BaseModel
  - type: "array" with scalar items.type -> list[<scalar>]

Degradation (D-02) -- everything else types to ``typing.Any`` with a
``# codegen: degraded -- <reason>`` comment directly above the field:
  - enum (any shape)              -> "enum not in v1.3 coverage"
  - oneOf                          -> "oneOf not in v1.3 coverage"
  - anyOf                          -> "anyOf not in v1.3 coverage"
  - $ref                           -> "$ref not in v1.3 coverage"
  - type: list (e.g. ["X","null"]) -> "multi-type / nullable not in v1.3 coverage"
  - array with non-scalar items    -> "array with non-scalar items not in v1.3 coverage"
  - unknown / missing type         -> "unknown type: <repr>"

CODEGEN-06: every emitted file starts with the AUTOGENERATED header.
D-03: `generate()` (added in Task 3) wipes generated/<slug>/ and writes fresh.

Pure-data: this module reads dicts and emits strings. No filesystem I/O in
``translate_tool``; ``generate`` (Task 3) owns ``shutil.rmtree`` + write_text.
"""
from __future__ import annotations

import json
import keyword
import re
from dataclasses import dataclass

from jsonschema.validators import Draft202012Validator, validator_for
from mcp.types import Tool

# `Draft202012Validator` + `validator_for` are referenced here per RESEARCH
# "Don't Hand-Roll" row 1 -- MCP tool schemas declare Draft 2020-12. We deliberately
# do NOT call `check_schema` (the full metaschema validator) because it rejects
# fields like `{"type": "color"}` outright; the walker's D-02 contract is to
# DEGRADE on unknown type tokens, not refuse. `_check_schema_structural`
# below catches structurally-broken schemas (e.g. `required: "not-a-list"`)
# without forcing every type token to be a JSON Schema primitive.
_ = (Draft202012Validator, validator_for)

from mcp_test_framework.sdet._slugs import module_name, pascal_case


HEADER_TEMPLATE = (
    "# AUTOGENERATED by mcp-test-framework gen-sdet-classes -- DO NOT HAND-EDIT.\n"
    "# Source: {slug} (serverInfo.name={server_name_repr}, version={server_version_repr})\n"
    "# Regenerated: {timestamp}\n"
    "# Extend by subclassing in tests/sdet/, not by editing this file.\n"
)


def _render_header(*, slug: str, server_name: str, server_version: str, timestamp: str) -> str:
    """Render HEADER_TEMPLATE with escaped server_name / server_version (CR-01).

    serverInfo.name / version flow from the MCP `initialize` handshake -- the
    server can advertise arbitrary strings, including embedded `"` / newlines
    that would close the Python comment early and inject executable source
    into the generated file (which Phase 18 then imports). We use
    `json.dumps(...)` to produce a safely-escaped double-quoted literal:
    embedded quotes, newlines, and unicode are all stringified into harmless
    escape sequences. The visible byte-for-byte form for safe inputs is
    unchanged (e.g. `homelab-mcp` -> `"homelab-mcp"`).
    """
    return HEADER_TEMPLATE.format(
        slug=slug,
        server_name_repr=json.dumps(server_name),
        server_version_repr=json.dumps(server_version),
        timestamp=timestamp,
    )


_SCALAR_MAP: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


@dataclass(frozen=True)
class FieldSpec:
    """A single Pydantic-model field as the walker plans it.

    py_type:        the post-`from __future__ import annotations` annotation
                    string (e.g. "str", "list[int]", "typing.Any").
    default_expr:   the right-hand side of `<name>: <py_type> = <default_expr>`.
                    For required fields this is `Field(...)`. For optional with
                    a default it is `Field(default=<repr>)`. For optional
                    without a default it is `Field(default=None)` and the type
                    becomes `<py_type> | None` (only at the top scalar level --
                    we don't degrade-then-nullable in v1.3 per D-02).
    degrade_reason: human-readable phrase if this field is a degradation,
                    else None. Emitted as `# codegen: degraded -- <reason>`
                    on the line above the field.
    default_is_none: True iff this field has no required-status AND no schema
                    default (so `_default_expr` produced `Field(default=None)`).
                    Structured signal consumed by `_format_field_line` to add
                    `| None` to the type annotation; replaces the previous
                    substring scan of `default_expr` for "default=None", which
                    false-positived on any field whose description contained the
                    literal "default=None" (reviewer issue #5).
    """
    py_type: str
    default_expr: str
    degrade_reason: str | None
    default_is_none: bool = False


class SchemaValidityError(ValueError):
    """Raised when an MCP tool's inputSchema is not a valid JSON Schema document.

    The codegen refuses to translate an invalid schema (loud-fail per CONTEXT.md
    Reusable Assets); the CLI command (Plan 17-04) maps this to an operator
    error naming the offending tool.
    """


def _check_schema_structural(tool_name: str, schema: dict) -> None:
    """Structural sanity check for a tool's inputSchema.

    Per Phase 17 RESEARCH "Don't Hand-Roll" row 1, MCP tool schemas are
    Draft 2020-12. We deliberately do NOT call
    `Draft202012Validator.check_schema(schema)` because the full metaschema
    rejects fields like `{"type":"color"}` -- and the walker's D-02 contract
    is to DEGRADE on unknown type tokens, not refuse the whole tool.

    This check catches the narrow class of malformed schemas the walker
    cannot operate on:
      - root `type:"object"` with `required` that is not a list
      - root `properties` that is not a dict (when present)

    Other shape weirdness (unknown type tokens, nested-object recursion,
    oneOf/anyOf/$ref combinators) falls through to `_emit_field` which
    degrades cleanly per D-02.
    """
    if not isinstance(schema, dict):
        return  # nothing to check; caller already coerced non-dicts away
    required = schema.get("required")
    if required is not None and not isinstance(required, list):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'required' must be a list, got "
            f"{type(required).__name__}). Refusing to translate."
        )
    props = schema.get("properties")
    if props is not None and not isinstance(props, dict):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'properties' must be an object, got "
            f"{type(props).__name__}). Refusing to translate."
        )


def _is_default_none(schema: dict, required: bool) -> bool:
    """True iff `_default_expr(schema, required)` emits `Field(default=None...)`.

    Reviewer issue #5: previously `_format_field_line` substring-matched
    `"default=None" in spec.default_expr` to decide whether to add `| None`
    to the type. That false-positived when a field's description literally
    contained the string `default=None`. This structured signal replaces it.
    """
    return (not required) and ("default" not in schema)


def _default_expr(schema: dict, required: bool) -> str:
    """Build the `Field(...)` right-hand side for a single field.

    Required fields get `Field(...)` (Ellipsis). Optional fields with a
    declared default get `Field(default=<repr>)`. Optional fields without
    a default get `Field(default=None)` -- and the type gets a `| None`
    union applied at emit-site (handled in _format_field_line) via the
    structured `FieldSpec.default_is_none` flag (NOT a substring scan --
    see `_is_default_none` and reviewer issue #5).

    description is lifted from schema["description"] if present; quoted via
    repr() for safe escaping.
    """
    desc = schema.get("description")
    desc_kwarg = f", description={desc!r}" if isinstance(desc, str) and desc else ""
    if required:
        return f"Field(...{desc_kwarg})"
    if "default" in schema:
        return f"Field(default={schema['default']!r}{desc_kwarg})"
    return f"Field(default=None{desc_kwarg})"


def _emit_field(schema: dict, *, required: bool) -> FieldSpec:
    """Translate one property's schema to a FieldSpec.

    WR-03: dropped the unused `name: str` parameter that lingered from an
    earlier draft. Callers no longer pass it. The JSON-Schema property
    name (and its safe-Python ident / alias) is owned by
    `_format_field_line`, which receives `name` separately.

    Order of checks matters: degradation triggers (enum/oneOf/anyOf/$ref/
    multi-type) take precedence over `type:` dispatch so that
    `{"type":"string","enum":["a","b"]}` degrades to Any (not str) per D-02.

    `default_is_none` is computed ONCE here via `_is_default_none` and
    threaded through every `FieldSpec(...)` construction (reviewer issue #5:
    replaces the previous substring scan of `default_expr` for "default=None",
    which false-positived on descriptions containing that literal).
    """
    is_none = _is_default_none(schema, required)
    # Degradation triggers (D-02) -- check FIRST.
    if "enum" in schema:
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "enum not in v1.3 coverage",
            default_is_none=is_none,
        )
    for combinator in ("oneOf", "anyOf", "$ref"):
        if combinator in schema:
            return FieldSpec(
                "typing.Any", _default_expr(schema, required),
                f"{combinator} not in v1.3 coverage",
                default_is_none=is_none,
            )
    jtype = schema.get("type")
    if isinstance(jtype, list):
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "multi-type / nullable not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Faithful translation paths (D-02).
    if isinstance(jtype, str) and jtype in _SCALAR_MAP:
        return FieldSpec(
            _SCALAR_MAP[jtype], _default_expr(schema, required), None,
            default_is_none=is_none,
        )
    if jtype == "array":
        items = schema.get("items") or {}
        items_type = items.get("type")
        if isinstance(items_type, str) and items_type in _SCALAR_MAP:
            return FieldSpec(
                f"list[{_SCALAR_MAP[items_type]}]",
                _default_expr(schema, required),
                None,
                default_is_none=is_none,
            )
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "array with non-scalar items not in v1.3 coverage",
            default_is_none=is_none,
        )
    if jtype == "object":
        # Nested objects in v1.3: degrade to dict[str, Any]; full nested-model
        # emission is a v1.4 expansion. The current goal is the walker + the
        # SEAM, not deep type fidelity (D-02 narrow promise).
        return FieldSpec(
            "dict[str, typing.Any]", _default_expr(schema, required),
            None if "properties" not in schema else
            "nested-object recursion not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Unknown / missing type.
    return FieldSpec(
        "typing.Any", _default_expr(schema, required),
        f"unknown type: {jtype!r}",
        default_is_none=is_none,
    )


_FIELD_NON_IDENT = re.compile(r"[^a-zA-Z0-9_]+")


def _safe_field_ident(name: str) -> tuple[str, str | None]:
    """Map a JSON-Schema property name to (python_ident, alias_if_renamed).

    CR-03: JSON-Schema property keys are arbitrary strings -- Python keywords
    (`class`, `import`), leading-digit (`2fa_code`), hyphenated (`vm-id`),
    whitespace / unicode (`vm id`, `配置`) all produce SyntaxError when
    interpolated verbatim into `<name>: <type> = Field(...)`. The slug and
    PascalCase helpers in `_slugs.py` already implement this guard for module
    and class names; the field path lacked an equivalent.

    Returns (ident, alias):
      - ident: the safe Python identifier to emit on the LHS of the field
        declaration.
      - alias: the original (wire) name, or None when no rename was needed.
        Callers thread alias through `Field(alias=<original>)` so Pydantic
        validates the wire field under its real name even though the Python
        attribute has been renamed.

    Sanitization strategy is close to `module_name` in `_slugs.py` but
    diverges on the leading-digit case: Pydantic v2 raises NameError on
    any field whose Python attribute name starts with "_" (interpreted as a
    private attr). So leading-digit / collapsed-to-empty names are prefixed
    with "f_" instead of "_", keeping the attribute public.

    Rules:
      - non-ident chars -> "_"
      - strip leading/trailing "_"
      - leading-digit / empty -> prefix "f_"
      - keyword -> suffix "_"
    """
    if name.isidentifier() and not keyword.iskeyword(name):
        return name, None
    ident = _FIELD_NON_IDENT.sub("_", name).strip("_")
    if not ident:
        # All-non-ident input (e.g. "---" or unicode-only) collapses to empty.
        ident = "f_field"
    elif ident[0].isdigit():
        # Pydantic rejects leading-underscore field names (NameError at class
        # construction), so use "f_" rather than the "_" prefix used by
        # `module_name` for module file names.
        ident = "f_" + ident
    if keyword.iskeyword(ident):
        ident = ident + "_"
    return ident, name


def _inject_alias(default_expr: str, alias: str) -> str:
    """Insert `alias=<repr(alias)>` as the first keyword argument inside Field(...).

    `default_expr` is always one of:
      - `Field(...)`                                    (required)
      - `Field(...,  description='...')`                (required + desc)
      - `Field(default=<repr>)`                         (optional with default)
      - `Field(default=<repr>, description='...')`      (optional with default + desc)
      - `Field(default=None)`                           (optional, no default)
      - `Field(default=None, description='...')`        (optional, no default + desc)

    All shapes start with literal `Field(` and end with `)`. We splice
    `alias=<repr>, ` immediately after the opening paren so it lands as the
    first keyword. The repr is via `json.dumps` for a safely-escaped
    double-quoted Python string literal.
    """
    assert default_expr.startswith("Field("), (
        f"_inject_alias: unexpected default_expr shape: {default_expr!r}"
    )
    head = "Field("
    rest = default_expr[len(head):]
    # `Field(...)` -- positional `...` is the required marker; alias goes AFTER
    # it as a kwarg, not before. Detect and splice after.
    if rest.startswith("..."):
        after_ellipsis = rest[3:]
        if after_ellipsis.startswith(", "):
            return f"Field(..., alias={json.dumps(alias)},{after_ellipsis[1:]}"
        if after_ellipsis.startswith(")"):
            return f"Field(..., alias={json.dumps(alias)}){after_ellipsis[1:]}"
        # Defensive fallback for any unexpected shape.
        return f"Field(..., alias={json.dumps(alias)}, {after_ellipsis}"
    # Kwarg-only forms: splice alias= as the first kwarg.
    return f"Field(alias={json.dumps(alias)}, {rest}"


def _format_field_line(name: str, spec: FieldSpec, *, required: bool) -> str:
    """Render a FieldSpec to source lines (degrade comment + field decl).

    Reviewer issue #5: this used to be `"default=None" in spec.default_expr`,
    which false-positived when a description happened to contain the literal
    string "default=None". We now consult the structured
    `FieldSpec.default_is_none` flag set by `_emit_field`.

    CR-03: `name` is the JSON-Schema property key (the wire-side name);
    `_safe_field_ident` maps it to a valid Python identifier, and any
    rename injects `alias=<original>` into the Field(...) call so Pydantic
    still validates the wire field under its real name.
    """
    py_type = spec.py_type
    # Optional fields without an explicit default get `| None`. Skip when the
    # type is already `typing.Any` (Any subsumes None). Phase 17 plan 17-05
    # pyright-strict gate caught the original predicate which also required
    # `degrade_reason is None` -- that excluded nested-object degradation paths
    # that still emit a concrete `dict[str, typing.Any]` type (not Any), so
    # pyright rejected `config: dict[str, Any] = Field(default=None)`. Any field
    # with default_is_none and a non-Any type needs `| None` regardless of
    # degrade status.
    if not required and spec.default_is_none and py_type != "typing.Any":
        py_type = f"{py_type} | None"
    # CR-03: sanitize the LHS identifier and inject alias= on rename.
    ident, alias = _safe_field_ident(name)
    default_expr = spec.default_expr
    if alias is not None:
        default_expr = _inject_alias(default_expr, alias)
    lines: list[str] = []
    if spec.degrade_reason is not None:
        lines.append(f"    # codegen: degraded -- {spec.degrade_reason}")
    lines.append(f"    {ident}: {py_type} = {default_expr}")
    return "\n".join(lines)


@dataclass(frozen=True)
class _BodyEmission:
    """Structured output of `_emit_params_body` / `_emit_response_body`.

    CR-04: replaces the previous `(body_text, degraded_count)` tuple plus
    post-render substring scans on the rendered text. The substring scan
    false-positived when a field description literally contained "typing."
    or "Field(" -- a description like "Accepts any typing.Any-compatible
    value" caused the emitter to write `import typing` against a body that
    never referenced typing.Any, resurrecting the orphaned-import shape
    Plan 17-06 was meant to close.

    Fields:
      body_text:        the rendered class body (with the trailing newline
                        the previous return shape already included).
      degraded_count:   how many fields fell to a typing.Any (or
                        dict[str, typing.Any]) degradation path.
      uses_typing_any:  True iff ANY emitted field's annotation references
                        `typing.` (covers both bare `typing.Any` and
                        composite `dict[str, typing.Any]`). Structured
                        signal -- consulted at the import-emission site
                        instead of substring-scanning the rendered body.
      has_fields:       True iff at least one `Field(...)` call was
                        emitted. False for `pass`-body classes (no
                        properties, non-object inputSchema, or None
                        outputSchema). Structured signal for the
                        conditional `from pydantic import ..., Field`.
    """
    body_text: str
    degraded_count: int
    uses_typing_any: bool
    has_fields: bool


def _emit_params_body(schema: dict | None) -> _BodyEmission:
    """Emit the body of a <Tool>Params class.

    Empty / non-object inputSchema -> `pass` body. degraded_count is 0 in
    that case and both `uses_typing_any` / `has_fields` are False.
    """
    if not isinstance(schema, dict) or schema.get("type") != "object":
        return _BodyEmission("    pass\n", 0, False, False)
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    if not props:
        return _BodyEmission("    pass\n", 0, False, False)
    degraded = 0
    uses_typing_any = False
    lines: list[str] = []
    # Required first (alphabetical), then optional (alphabetical) -- matches
    # `_format_param_signature` at cli.py:932-950.
    req_names = sorted(n for n in props if n in required)
    opt_names = sorted(n for n in props if n not in required)
    for name in req_names + opt_names:
        prop_schema = props[name] if isinstance(props[name], dict) else {}
        spec = _emit_field(prop_schema, required=(name in required))
        if spec.degrade_reason is not None:
            degraded += 1
        if "typing." in spec.py_type:
            uses_typing_any = True
        lines.append(_format_field_line(name, spec, required=(name in required)))
    # `lines` is non-empty here because `props` is non-empty and we iterate
    # over both required and optional names. `has_fields=True`.
    return _BodyEmission(
        body_text="\n".join(lines) + "\n",
        degraded_count=degraded,
        uses_typing_any=uses_typing_any,
        has_fields=True,
    )


def _emit_response_body(schema: dict | None) -> _BodyEmission:
    """Emit the body of a <Tool>Response class. D-06 stub when schema is None."""
    if schema is None:
        return _BodyEmission("    pass\n", 0, False, False)
    # When outputSchema IS declared, treat it the same as Params (object walk).
    return _emit_params_body(schema)


def translate_tool(
    tool: Tool,
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
) -> tuple[str, int]:
    """Translate one MCP Tool to a per-tool source file (str). Pure-data.

    Returns (source_text, degraded_field_count).

    Refuses to translate if `tool.inputSchema` is not a valid JSON Schema
    document (raises SchemaValidityError per "Don't Hand-Roll" row 1).
    """
    input_schema = tool.inputSchema if isinstance(tool.inputSchema, dict) else {}
    if input_schema:
        _check_schema_structural(tool.name, input_schema)

    cls_base = pascal_case(tool.name)
    header = _render_header(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )

    params = _emit_params_body(input_schema)
    output_schema = tool.outputSchema if isinstance(tool.outputSchema, dict) else None
    response = _emit_response_body(output_schema)

    response_class = (
        f"class {cls_base}Response(ToolResponse):\n"
        f'    """Typed response for the `{tool.name}` tool.\n\n'
        f"    Inherits .raw / .data / .text / .is_error from ToolResponse (CODEGEN-04).\n"
    )
    if output_schema is None:
        # D-06: stub class -- pass body, document the lack of outputSchema.
        response_class += (
            f"    outputSchema was undeclared at codegen time; .data falls\n"
            f"    back to JSON-parse / text-dict per CODEGEN-04 chain.\n"
            f'    """\n'
            f"{response.body_text}"
        )
    else:
        response_class += f'    """\n{response.body_text}'

    # Gap-1 fix (Plan 17-06) + CR-04: emit `import typing` / `Field` only
    # when the body actually uses them. The previous scan was a substring
    # check over the rendered body (`"typing." in body_text`,
    # `"Field(" in body_text`), which false-positived when a field's
    # description literally contained "typing." or "Field(" -- resurrecting
    # the orphaned-import shape pyright-strict's reportUnusedImport rejects.
    # `_BodyEmission` now threads `uses_typing_any` / `has_fields` as
    # structured signals computed at field-emission time (over the typed
    # FieldSpec, not the rendered string), so descriptions can't poison the
    # decision.
    needs_typing = params.uses_typing_any or response.uses_typing_any
    needs_field = params.has_fields or response.has_fields

    pydantic_imports = "BaseModel, ConfigDict"
    if needs_field:
        pydantic_imports += ", Field"
    typing_import_line = "import typing\n\n" if needs_typing else ""

    source = (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"{typing_import_line}"
        f"from pydantic import {pydantic_imports}\n\n"
        f"from mcp_test_framework.sdet.response import ToolResponse\n\n\n"
        f"class {cls_base}Params(BaseModel):\n"
        f'    """Params for the `{tool.name}` tool.\n\n'
        f"    Generated from inputSchema. Pydantic validates required / type /\n"
        f"    default rules at construction time before the wire call.\n"
        f'    """\n'
        f"    model_config = ConfigDict(extra=\"forbid\")\n\n"
        f"{params.body_text}\n\n"
        f"{response_class}"
    )
    return source, params.degraded_count + response.degraded_count


# --- File emission (D-03 wipe-and-write) ----------------------------------

import datetime as _dt
import shutil
from pathlib import Path

from mcp_test_framework.sdet._slugs import server_slug


def _render_init(
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
    registry_entries: list[tuple[str, str]],  # [(tool_name, pascal_base), ...]
) -> str:
    """Render generated/<slug>/__init__.py: header + per-tool imports + _REGISTRY.

    Per RESEARCH Pattern 4 + CONTEXT.md "What gen-sdet-classes prints" (sorted).
    """
    header = _render_header(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )
    # Imports, sorted alphabetically by tool_name (diff-stable).
    import_lines: list[str] = []
    all_names: list[str] = []
    registry_lines: list[str] = []
    for tool_name, pascal in sorted(registry_entries, key=lambda t: t[0]):
        params_cls = f"{pascal}Params"
        response_cls = f"{pascal}Response"
        mod = module_name(tool_name)
        import_lines.append(f"from .{mod} import {params_cls}, {response_cls}")
        all_names.extend([f'"{params_cls}"', f'"{response_cls}"'])
        # CR-02: json.dumps()-escape tool_name so a server-advertised name
        # containing `"` / newline cannot close the dict-key string literal
        # and inject a callable into the registry dict (which Phase 18's
        # factory then dispatches against). For names that match the MCP
        # spec regex `[A-Za-z_][A-Za-z0-9_]*` the visible form is identical
        # to the prior `f'"{tool_name}"'` interpolation.
        registry_lines.append(
            f"    {json.dumps(tool_name)}: ({params_cls}, {response_cls}),"
        )

    all_block = "__all__ = [\n    " + ",\n    ".join(all_names) + ",\n]" if all_names else "__all__ = []"
    # WR-02: emit the tighter `type[BaseModel]` annotation to match
    # _tool_factory._REGISTRIES expectations. Downstream consumers of the
    # generated _REGISTRY see a typed Pydantic model class, not bare `type`.
    registry_block = (
        "# Phase 17 CODEGEN-05: tool(name) factory dispatches against this.\n"
        "# Phase 18 will consume _REGISTRY through "
        "`mcp_test_framework.sdet._tool_factory`.\n"
        "_REGISTRY: dict[str, tuple[type[BaseModel], type[ToolResponse]]] = {\n"
        + "\n".join(registry_lines) + "\n}\n"
    ) if registry_lines else (
        "_REGISTRY: dict[str, tuple[type[BaseModel], type[ToolResponse]]] = {}\n"
    )

    body = "\n".join(import_lines) + ("\n\n" if import_lines else "")
    return (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"from pydantic import BaseModel\n\n"
        f"from mcp_test_framework.sdet.response import ToolResponse\n\n"
        f"{body}"
        f"{all_block}\n\n"
        f"{registry_block}"
    )


def generate(
    *,
    server_name: str,
    server_version: str,
    tools: list[Tool],
    out_root: Path,
    timestamp: str | None = None,
) -> dict[str, int]:
    """Wipe-and-write generated/<slug>/ from a list of Tool objects.

    D-03: shutil.rmtree(target, ignore_errors=True) -> mkdir -> write per-tool
    files -> write __init__.py LAST (Pitfall 5: partial states fail clean,
    not half-imported).

    `timestamp=None` uses datetime.now(UTC) at sub-second precision; tests
    pass a fixed value for byte-identical idempotency.

    Returns counts: {"tools": <N>, "degraded_fields": <M>}.
    """
    if timestamp is None:
        timestamp = _dt.datetime.now(_dt.UTC).isoformat(timespec="seconds")

    slug = server_slug(server_name)  # raises ValueError on empty/all-non-ident
    target = out_root / slug

    # D-03 wipe.
    shutil.rmtree(target, ignore_errors=True)
    target.mkdir(parents=True, exist_ok=True)

    counts = {"tools": 0, "degraded_fields": 0}
    registry_entries: list[tuple[str, str]] = []

    # Sorted emission for diff-stability.
    for tool in sorted(tools, key=lambda t: t.name):
        rendered, degraded_n = translate_tool(
            tool, slug=slug, server_name=server_name,
            server_version=server_version, timestamp=timestamp,
        )
        per_tool_path = target / f"{module_name(tool.name)}.py"
        per_tool_path.write_text(rendered, encoding="utf-8")
        counts["tools"] += 1
        counts["degraded_fields"] += degraded_n
        registry_entries.append((tool.name, pascal_case(tool.name)))

    # Write __init__.py LAST (Pitfall 5).
    init_text = _render_init(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
        registry_entries=registry_entries,
    )
    (target / "__init__.py").write_text(init_text, encoding="utf-8")

    return counts
