"""ToolResponse base -- uniform .raw / .data / .text / .is_error per CODEGEN-04.

Per Phase 17 CONTEXT.md decisions:
  - D-07: Pydantic v2 BaseModel with @computed_field properties; lazy
    evaluation via @property (NOT eager-parsed at construction). Subclasses
    inherit accessors and may add typed fields (typed Response classes when
    outputSchema is declared) or remain stubs (D-06: stub when undeclared).
  - D-04: pyright is the static-type-check verifier; this module must be
    pyright-strict-clean.

CODEGEN-04 .data fallback chain (locked):
  1. raw.structuredContent if present
  2. else: JSON-parse first TextContent (must parse to a dict)
  3. else: {"text": <concat of all TextContent>} if any text exists
  4. else: None

Phase 17 boundary: this module ships the BASE only. Generated <Tool>Response
classes (created by `gen-sdet-classes`, Plan 17-04) inherit from ToolResponse
and either pass-stub or add typed fields. The .call() runtime that constructs
ToolResponse instances is wired in Phase 18 (mcp_session fixture).

Pitfall 7 (17-RESEARCH.md): CallToolResult.content is heterogeneous
(TextContent | ImageContent | AudioContent | ResourceLink | EmbeddedResource).
.text MUST filter on isinstance(block, TextContent) -- never .getattr('text')
naively.
"""
from __future__ import annotations

import json
from typing import Any

from mcp.types import CallToolResult, TextContent
from pydantic import BaseModel, ConfigDict, computed_field


class ToolResponse(BaseModel):
    """Uniform response surface for every MCP tool, regardless of outputSchema.

    Subclasses generated by ``gen-sdet-classes`` either add typed fields (when
    outputSchema is declared) or are stubs (``class FooResponse(ToolResponse):
    pass`` per D-06).
    """

    # arbitrary_types_allowed: CallToolResult is itself a Pydantic model from
    # `mcp.types` but Pydantic v2 strict mode requires this opt-in for any
    # external model used as a field type.
    model_config = ConfigDict(arbitrary_types_allowed=True)

    raw: CallToolResult

    @computed_field
    @property
    def is_error(self) -> bool:
        """Mirror of raw.isError (CODEGEN-04)."""
        return self.raw.isError

    @computed_field
    @property
    def text(self) -> str:
        """Concatenated TextContent.text across all content blocks.

        Non-TextContent blocks (Image/Audio/ResourceLink/EmbeddedResource) are
        silently skipped -- see Pitfall 7 in 17-RESEARCH.md. Naive
        ``b.text for b in raw.content`` would AttributeError on ImageContent.
        """
        return "".join(
            b.text for b in self.raw.content
            if isinstance(b, TextContent)
        )

    @computed_field
    @property
    def data(self) -> dict[str, Any] | None:
        """Best-effort dict view per CODEGEN-04 fallback chain.

        Order:
          1. raw.structuredContent if present (return as-is, even if empty dict)
          2. JSON-parse of first TextContent.text -- only counted if it parses
             to a dict (lists / scalars / null fall through)
          3. {"text": <concatenated text>} if any text content exists
          4. None

        Note: does NOT check is_error. Phase 18's tool().call() raises
        ToolCallError on isError=True; .data here returns whatever payload
        the server sent (Pitfall 8 in 17-RESEARCH.md).
        """
        if self.raw.structuredContent is not None:
            return self.raw.structuredContent
        for block in self.raw.content:
            if isinstance(block, TextContent):
                try:
                    parsed = json.loads(block.text)
                except (json.JSONDecodeError, ValueError):
                    parsed = None
                if isinstance(parsed, dict):
                    return parsed
                break  # only try the FIRST TextContent (CODEGEN-04 spec)
        concat = self.text
        if concat:
            return {"text": concat}
        return None
