"""Unit tests for mcp_test_framework.test_code._codegen.generate (CODEGEN-01, D-03, D-06).

Pins:
  - file layout: one file per tool + __init__.py
  - header marker presence on every emitted file (CODEGEN-06)
  - idempotence: held-fixed timestamp + same input -> byte-identical output
  - wipe-and-write: stale files inside generated/<slug>/ removed on re-run (D-03)
  - write order: per-tool files first, __init__.py LAST (Pitfall 5 in 17-RESEARCH.md)
  - _REGISTRY entry per tool (Phase 17 -> Phase 18 seam)
  - sanitized tool names produce snake_case module files (Pitfall 2)
"""
from __future__ import annotations

from pathlib import Path

import pytest
from mcp.types import Tool

from mcp_test_framework.test_code._codegen import generate


_FIXED_TS = "2026-05-12T14:23:01+00:00"


def _t(name: str, *, input_schema: dict | None = None, output_schema: dict | None = None) -> Tool:
    return Tool(
        name=name,
        description=f"Test tool {name}",
        inputSchema=input_schema if input_schema is not None else {"type": "object", "properties": {}, "required": []},
        outputSchema=output_schema,
    )


def test_emitter_writes_one_file_per_tool_plus_init(tmp_path: Path) -> None:
    counts = generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("create_vm"), _t("delete_vm")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    slug_dir = tmp_path / "homelab_mcp"
    assert (slug_dir / "create_vm.py").is_file()
    assert (slug_dir / "delete_vm.py").is_file()
    assert (slug_dir / "__init__.py").is_file()
    assert counts == {"tools": 2, "degraded_fields": 0}


def test_emitter_header_marker_on_every_file(tmp_path: Path) -> None:
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("create_vm")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    for py_file in (tmp_path / "homelab_mcp").glob("*.py"):
        text = py_file.read_text(encoding="utf-8")
        assert "# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT." in text, py_file
        assert "# Extend by subclassing in tests/test_code/, not by editing this file." in text, py_file


def test_emitter_is_idempotent_with_fixed_timestamp(tmp_path: Path) -> None:
    """D-03 idempotence: same input -> byte-identical output."""
    tools = [_t("create_vm"), _t("delete_vm"), _t("list-registered-servers")]
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
    )
    first_files = {p.name: p.read_bytes() for p in (tmp_path / "homelab_mcp").glob("*.py")}
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
    )
    second_files = {p.name: p.read_bytes() for p in (tmp_path / "homelab_mcp").glob("*.py")}
    assert first_files == second_files


def test_emitter_wipes_stale_files(tmp_path: Path) -> None:
    """D-03 wipe-and-write: stale files removed on re-run."""
    slug_dir = tmp_path / "homelab_mcp"
    slug_dir.mkdir(parents=True)
    (slug_dir / "stale_file.py").write_text("# operator-edited content\n")
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("create_vm")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    assert not (slug_dir / "stale_file.py").exists()
    assert (slug_dir / "create_vm.py").exists()


def test_emitter_writes_init_py_last(tmp_path: Path) -> None:
    """Pitfall 5: __init__.py is the LAST file written so partial states fail
    clean. Verify by mtime ordering across a synthetic multi-tool fixture."""
    tools = [_t("create_vm"), _t("delete_vm"), _t("modify_vm")]
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
    )
    slug_dir = tmp_path / "homelab_mcp"
    init_mtime = (slug_dir / "__init__.py").stat().st_mtime_ns
    other_mtimes = [
        p.stat().st_mtime_ns
        for p in slug_dir.glob("*.py")
        if p.name != "__init__.py"
    ]
    assert other_mtimes, "expected per-tool files to exist"
    assert init_mtime >= max(other_mtimes), (
        f"__init__.py mtime ({init_mtime}) should be >= max per-tool mtime "
        f"({max(other_mtimes)}); Pitfall 5 write-order violated."
    )


def test_emitter_init_py_carries_registry(tmp_path: Path) -> None:
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("create_vm"), _t("delete_vm")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    init_text = (tmp_path / "homelab_mcp" / "__init__.py").read_text(encoding="utf-8")
    # Header
    assert "# AUTOGENERATED by mcp-test-framework gen-test-classes" in init_text
    # Per-tool imports
    assert "from .create_vm import CreateVmParams, CreateVmResponse" in init_text
    assert "from .delete_vm import DeleteVmParams, DeleteVmResponse" in init_text
    # __all__
    assert '"CreateVmParams"' in init_text
    assert '"DeleteVmResponse"' in init_text
    # _REGISTRY for Phase 18 dispatch -- WR-02 tightened annotation from bare
    # `type` to `type[BaseModel]` to match _tool_factory._REGISTRIES.
    assert "_REGISTRY: dict[str, tuple[type[BaseModel], type[ToolResponse]]] = {" in init_text
    assert "from pydantic import BaseModel" in init_text
    assert '"create_vm": (CreateVmParams, CreateVmResponse),' in init_text


def test_emitter_sanitizes_kebab_tool_name(tmp_path: Path) -> None:
    """Pitfall 2: tool name with hyphens produces snake_case module file."""
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("list-registered-servers")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    slug_dir = tmp_path / "homelab_mcp"
    assert (slug_dir / "list_registered_servers.py").exists()
    init_text = (slug_dir / "__init__.py").read_text(encoding="utf-8")
    assert "from .list_registered_servers import ListRegisteredServersParams, ListRegisteredServersResponse" in init_text


def test_emitter_counts_degraded_fields(tmp_path: Path) -> None:
    tools = [_t("create_vm", input_schema={
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "os_type": {"type": "string", "enum": ["linux", "windows"]},  # degrades
            "target": {"oneOf": [{"type": "string"}]},                    # degrades
        },
        "required": ["name", "os_type"],
    })]
    counts = generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
    )
    assert counts == {"tools": 1, "degraded_fields": 2}


def test_emitter_loud_fail_on_empty_server_name(tmp_path: Path) -> None:
    """D-05: empty serverInfo.name -> ValueError (CLI maps to operator error
    in Plan 17-04). Codegen layer is loud at the slug boundary."""
    with pytest.raises(ValueError, match="empty slug"):
        generate(
            server_name="", server_version="0.0.0",
            tools=[_t("create_vm")],
            out_root=tmp_path, timestamp=_FIXED_TS,
        )


def test_emitter_omits_unused_typing_import_when_no_typing_any(tmp_path: Path) -> None:
    """Gap-1 regression (17-HUMAN-UAT): a tool with no params and no
    typing.Any degradation MUST NOT emit `import typing`. Pyright strict's
    reportUnusedImport otherwise fails for this shape against live homelab-mcp.
    """
    # Empty-params tool: no fields -> no `Field(` calls AND no `typing.Any`.
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("ping")],  # _t default schema: {"type":"object","properties":{},"required":[]}
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    text = (tmp_path / "homelab_mcp" / "ping.py").read_text(encoding="utf-8")
    # The bug: pre-fix emitter wrote `import typing` unconditionally.
    assert "import typing" not in text, (
        f"empty-params tool unexpectedly emitted `import typing`; "
        f"this is the Gap-1 regression. File text:\n{text}"
    )


def test_emitter_omits_unused_field_import_when_no_field_calls(tmp_path: Path) -> None:
    """Gap-1 regression (17-HUMAN-UAT): a tool whose rendered body contains
    no `Field(` calls MUST NOT include `Field` in the pydantic import.
    """
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("ping")],
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    text = (tmp_path / "homelab_mcp" / "ping.py").read_text(encoding="utf-8")
    # Pydantic import line should be `from pydantic import BaseModel, ConfigDict`
    # without `Field`. Allow either ordering robustness via two assertions:
    assert "from pydantic import BaseModel, ConfigDict\n" in text, (
        f"expected pydantic import without Field; got file text:\n{text}"
    )
    assert ", Field" not in text and "Field," not in text and "Field\n" not in text, (
        f"Field unexpectedly imported despite no Field(...) usage. File text:\n{text}"
    )


def test_emitter_still_emits_typing_and_field_when_used(tmp_path: Path) -> None:
    """Positive control: a tool whose rendered body DOES use typing.Any
    (via degradation) AND Field(default=...) (via optional with default)
    MUST still emit both imports.
    """
    tools = [_t("create_vm", input_schema={
        "type": "object",
        "properties": {
            "kind": {"type": "string", "enum": ["a", "b"]},  # degrades -> typing.Any
            "count": {"type": "integer", "default": 1},      # optional with default -> Field(default=1)
        },
        "required": ["kind"],
    })]
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
    )
    text = (tmp_path / "homelab_mcp" / "create_vm.py").read_text(encoding="utf-8")
    assert "import typing\n" in text, f"typing should be imported (degraded field uses typing.Any). File:\n{text}"
    assert "from pydantic import BaseModel, ConfigDict, Field\n" in text, (
        f"Field should be imported (count uses Field(default=1)). File:\n{text}"
    )


# ---------------------------------------------------------------------------
# Phase 999.2 / GEN-02: tools_config kwarg + per-tool smoke file emission
# ---------------------------------------------------------------------------

class _ToolCfgShim:
    """Duck-typed stand-in for ToolConfig -- only needs .examples for the generate() loop."""
    def __init__(self, examples=None):
        self.examples = examples


def test_generate_accepts_tools_config_kwarg_when_omitted(tmp_path: Path) -> None:
    """Backward-compat: existing callers passing no tools_config kwarg still work."""
    t = _t("create_vm")  # required: []
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
    )
    assert (tmp_path / "homelab_mcp" / "create_vm.py").exists()
    assert (tmp_path / "homelab_mcp" / "__init__.py").exists()


def test_generate_emits_smoke_file_for_required_field_tool_with_examples(tmp_path: Path) -> None:
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}, "name": {"type": "string"}},
        "required": ["vmid", "name"],
    })
    tools_cfg = {"create_vm": _ToolCfgShim(examples=[{"vmid": 9001, "name": "smoke"}])}
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    smoke = (tmp_path / "homelab_mcp" / "create_vm_call_smoke.py").read_text(encoding="utf-8")
    assert "@pytest.mark.asyncio(loop_scope=\"session\")" in smoke
    assert "from .create_vm import CreateVmParams" in smoke
    assert "pytest.skip" not in smoke  # examples-present, NOT the TODO branch
    assert "await tool(\"create_vm\").call(params)" in smoke


def test_generate_emits_todo_smoke_file_for_required_field_tool_without_examples(tmp_path: Path) -> None:
    """D-02: required-field tool with no tools_config entry -> TODO/skip module emitted."""
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}, "name": {"type": "string"}},
        "required": ["vmid", "name"],
    })
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=None,  # explicit None -- operator has no examples: for this tool
    )
    smoke = (tmp_path / "homelab_mcp" / "create_vm_call_smoke.py").read_text(encoding="utf-8")
    assert "pytest.skip(" in smoke
    assert "allow_module_level=True" in smoke
    # D-02a grep-able reason
    assert "populate tools.create_vm.examples: in config.yaml to enable this smoke" in smoke
    # D-02 -- module remains fully importable: relative import still present
    assert "from .create_vm import CreateVmParams" in smoke


def test_generate_does_not_emit_smoke_file_for_no_required_field_tool(tmp_path: Path) -> None:
    """GEN-02 zero-output: required: [] -> no <tool>_call_smoke.py."""
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[_t("ping")],  # default _t() -> required: []
        out_root=tmp_path, timestamp=_FIXED_TS,
    )
    assert not (tmp_path / "homelab_mcp" / "ping_call_smoke.py").exists()
    assert (tmp_path / "homelab_mcp" / "ping.py").exists()  # <tool>.py still emitted


def test_generate_writes_init_py_after_smoke_files(tmp_path: Path) -> None:
    """Init-last invariant (Pitfall 5): smoke files must be written BEFORE __init__.py
    so a partial generate() failure leaves a broken state that fails clean rather than
    being half-imported.
    """
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}},
        "required": ["vmid"],
    })
    tools_cfg = {"create_vm": _ToolCfgShim(examples=[{"vmid": 9001}])}
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    smoke_path = tmp_path / "homelab_mcp" / "create_vm_call_smoke.py"
    init_path = tmp_path / "homelab_mcp" / "__init__.py"
    assert smoke_path.exists() and init_path.exists()
    # init_path written last (or simultaneously) -- never before
    assert smoke_path.stat().st_mtime_ns <= init_path.stat().st_mtime_ns
