"""Unit tests for mcp_test_framework.test_code._codegen + _slugs.

Pins:
  - _slugs: D-05 server_slug normalization, pascal_case / module_name keyword + digit guards
  - _codegen.translate_tool: D-02 schema coverage rules + degradation comments
    (D-02 enum/oneOf/anyOf/$ref/nullable/array-non-scalar/unknown-type)
  - CODEGEN-06 header marker presence
  - CODEGEN-03 D-06 stub Response for outputSchema-undeclared tools

Pure-sync (no asyncio). Walker is a pure-data transform; no I/O here.
"""
from __future__ import annotations

import pytest

from mcp_test_framework.test_code._slugs import module_name, pascal_case, server_slug


# --- _slugs ----------------------------------------------------------------

class TestServerSlug:
    def test_homelab_mcp(self) -> None:
        assert server_slug("homelab-mcp") == "homelab_mcp"

    def test_mixed_case_and_dots(self) -> None:
        assert server_slug("My Server v2.0") == "my_server_v2_0"

    def test_collapses_runs_and_strips(self) -> None:
        assert server_slug("___leading-trailing___") == "leading_trailing"

    def test_empty_raises(self) -> None:
        with pytest.raises(ValueError, match="empty slug"):
            server_slug("")

    def test_whitespace_only_raises(self) -> None:
        with pytest.raises(ValueError, match="empty slug"):
            server_slug("   ")


class TestPascalCase:
    def test_snake_case(self) -> None:
        assert pascal_case("create_vm") == "CreateVm"

    def test_kebab_case(self) -> None:
        assert pascal_case("list-registered-servers") == "ListRegisteredServers"

    def test_keyword_guard(self) -> None:
        assert pascal_case("class") == "Class_"

    def test_leading_digit_guard(self) -> None:
        assert pascal_case("2nd_attempt") == "_2ndAttempt"

    def test_empty_raises(self) -> None:
        with pytest.raises(ValueError, match="no identifier characters"):
            pascal_case("")

    def test_homelab_mcp_tool_set_no_collisions(self) -> None:
        """Pitfall 2: adversarial real-world names round-trip without collision."""
        names = [
            "list_registered_servers",
            "create_vm",
            "delete-vm",
            "check_proxmox_health",
            "import",
            "2fa-verify",
            "class",
        ]
        pascals = [pascal_case(n) for n in names]
        assert len(set(pascals)) == len(names), f"collisions: {pascals}"


class TestModuleName:
    def test_snake_passthrough(self) -> None:
        assert module_name("create_vm") == "create_vm"

    def test_kebab_to_snake(self) -> None:
        assert module_name("list-registered-servers") == "list_registered_servers"

    def test_keyword_guard(self) -> None:
        assert module_name("import") == "import_"

    def test_leading_digit_guard(self) -> None:
        assert module_name("2nd-attempt") == "_2nd_attempt"


# --- _codegen.translate_tool ----------------------------------------------

from mcp.types import Tool

from mcp_test_framework.test_code._codegen import (
    SchemaValidityError,
    translate_tool,
)


def _t(name: str, *, input_schema: dict | None = None, output_schema: dict | None = None) -> Tool:
    return Tool(
        name=name,
        description=f"Test tool {name}",
        inputSchema=input_schema if input_schema is not None else {"type": "object", "properties": {}, "required": []},
        outputSchema=output_schema,
    )


_FIXED_TS = "2026-05-12T14:23:01+00:00"
_FIXED_HEADER_KW = {"slug": "homelab_mcp", "server_name": "homelab-mcp", "server_version": "0.5.2", "timestamp": _FIXED_TS}


class TestWalkerHeader:
    def test_emits_autogenerated_header_verbatim(self) -> None:
        src, _ = translate_tool(_t("create_vm"), **_FIXED_HEADER_KW)
        assert "# AUTOGENERATED by mcp-test-framework gen-sdet-classes -- DO NOT HAND-EDIT." in src
        assert "# Extend by subclassing in tests/sdet/, not by editing this file." in src
        assert "serverInfo.name=\"homelab-mcp\"" in src
        assert _FIXED_TS in src

    def test_emits_future_annotations_and_pydantic_imports(self) -> None:
        # Plan 17-06 Gap-1 fix: `import typing` and `Field` are now CONDITIONAL
        # on actual usage in the rendered body (pyright strict reportUnusedImport).
        # Use a tool whose body exercises BOTH: a degraded enum (forces `typing.Any`)
        # and a required scalar field (forces `Field(...)`).
        tool = _t("create_vm", input_schema={
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "kind": {"type": "string", "enum": ["a", "b"]},  # degrades -> typing.Any
            },
            "required": ["name", "kind"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "from __future__ import annotations" in src
        assert "from pydantic import BaseModel, ConfigDict, Field" in src
        assert "from mcp_test_framework.test_code.response import ToolResponse" in src
        assert "import typing" in src


class TestWalkerScalarCoverage:
    def test_string_field(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"name": {"type": "string"}},
            "required": ["name"],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "name: str = Field(...)" in src
        assert deg == 0

    def test_integer_with_default(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"cpus": {"type": "integer", "default": 2}},
            "required": [],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "cpus: int = Field(default=2)" in src
        assert deg == 0

    def test_number_maps_to_float(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"weight": {"type": "number"}},
            "required": ["weight"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "weight: float = Field(...)" in src

    def test_boolean_field(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"enabled": {"type": "boolean"}},
            "required": ["enabled"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "enabled: bool = Field(...)" in src

    def test_array_of_scalar(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"tags": {"type": "array", "items": {"type": "string"}}},
            "required": ["tags"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "tags: list[str] = Field(...)" in src


class TestWalkerDegradation:
    def test_enum_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"os_type": {"type": "string", "enum": ["linux", "windows"]}},
            "required": ["os_type"],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "# codegen: degraded -- enum not in v1.3 coverage" in src
        assert "os_type: typing.Any" in src
        assert deg == 1

    def test_oneOf_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"target": {"oneOf": [{"type": "string"}, {"type": "integer"}]}},
            "required": ["target"],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "# codegen: degraded -- oneOf not in v1.3 coverage" in src
        assert "target: typing.Any" in src
        assert deg == 1

    def test_anyOf_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"target": {"anyOf": [{"type": "string"}, {"type": "integer"}]}},
            "required": ["target"],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "anyOf not in v1.3 coverage" in src
        assert deg == 1

    def test_ref_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"target": {"$ref": "#/$defs/Other"}},
            "required": [],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "$ref not in v1.3 coverage" in src
        assert deg == 1

    def test_nullable_multi_type_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"target": {"type": ["string", "null"]}},
            "required": [],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "multi-type / nullable not in v1.3 coverage" in src
        assert deg == 1

    def test_array_non_scalar_items_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"items": {"type": "array", "items": {"type": "object"}}},
            "required": [],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "array with non-scalar items not in v1.3 coverage" in src
        assert deg == 1

    def test_unknown_type_degrades(self) -> None:
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {"weird": {"type": "color"}},
            "required": [],
        })
        src, deg = translate_tool(tool, **_FIXED_HEADER_KW)
        assert "unknown type:" in src
        assert deg == 1


class TestWalkerEmitsExtraForbidOnParams:
    def test_walker_emits_extra_forbid_on_params(self) -> None:
        src, _ = translate_tool(_t("create_vm"), **_FIXED_HEADER_KW)
        # Params class MUST carry extra="forbid" (Claude's Discretion last bullet)
        params_section = src.split("class CreateVmResponse")[0]
        assert 'model_config = ConfigDict(extra="forbid")' in params_section

    def test_walker_does_not_emit_extra_forbid_on_response(self) -> None:
        # Response is server-controlled output; do NOT lock its shape.
        tool = _t("create_vm", output_schema={"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]})
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        response_section = src.split("class CreateVmResponse")[1]
        assert 'extra="forbid"' not in response_section


class TestWalkerStubResponse:
    def test_undeclared_output_schema_emits_stub(self) -> None:
        """D-06: outputSchema is None -> stub class with pass body."""
        src, _ = translate_tool(_t("create_vm", output_schema=None), **_FIXED_HEADER_KW)
        assert "class CreateVmResponse(ToolResponse):" in src
        # The stub body has a pass after the docstring.
        response_section = src.split("class CreateVmResponse(ToolResponse):")[1]
        assert "pass" in response_section


class TestWalkerSchemaValidityPreflight:
    def test_invalid_schema_raises_loud(self) -> None:
        """'Don't Hand-Roll' row 1: refuse to translate an invalid JSON Schema."""
        # type: "object" with required NOT a list -> SchemaError under Draft 2020-12
        tool = _t("t", input_schema={"type": "object", "required": "not-a-list"})
        with pytest.raises(SchemaValidityError, match="not a valid JSON Schema"):
            translate_tool(tool, **_FIXED_HEADER_KW)


class TestWalkerOrderingStable:
    def test_required_first_then_alphabetical(self) -> None:
        """Required fields first (alphabetical), then optional (alphabetical) --
        matches the cli._format_param_signature precedent at cli.py:932-950."""
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {
                "zeta": {"type": "string"},
                "alpha": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["name"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        # Find positions of field declarations
        i_name = src.index("name: str")
        i_alpha = src.index("alpha: str")
        i_zeta = src.index("zeta: str")
        assert i_name < i_alpha < i_zeta, f"Order: name={i_name}, alpha={i_alpha}, zeta={i_zeta}"


class TestWalkerNullableUsesStructuredSignal:
    """Reviewer issue #5: `_format_field_line` previously did a substring
    scan of `spec.default_expr` for "default=None" to decide whether to add
    `| None` to the type. That false-positived when a description literally
    contained the string "default=None". The walker now consults the
    structured `FieldSpec.default_is_none` flag set by `_emit_field` via
    `_is_default_none`. These tests pin both directions of the fix."""

    def test_required_field_with_default_none_in_description_NOT_marked_nullable(self) -> None:
        """A REQUIRED field whose description literally contains the string
        'default=None' must NOT be marked `| None` -- it is required, so the
        annotation is just `str`, even though the old substring scan would
        have spuriously matched the description text."""
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "When omitted (the parameter has default=None upstream), the server picks a name.",
                },
            },
            "required": ["name"],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        params_section = src.split("class TResponse")[0]
        # Required, so line is `name: str = Field(...,`. The substring
        # "default=None" appears in the description -- the OLD substring scan
        # would have wrongly typed this as `str | None`.
        assert "name: str = Field(..." in params_section
        assert "name: str | None" not in params_section

    def test_optional_field_with_real_default_and_default_none_in_description_NOT_marked_nullable(self) -> None:
        """An OPTIONAL field with an EXPLICIT default whose description
        literally contains 'default=None' must NOT be marked `| None`. The
        field has a real default, so `_is_default_none` returns False even
        though the substring scan would have matched the description."""
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "default": "anon",
                    "description": "Server-side default=None is deprecated; we ship 'anon' here.",
                },
            },
            "required": [],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        params_section = src.split("class TResponse")[0]
        # Default is "anon", not None, so type stays bare `str`.
        assert "name: str = Field(default='anon'" in params_section
        assert "name: str | None" not in params_section

    def test_optional_field_with_no_default_IS_marked_nullable(self) -> None:
        """Positive case: the actual `| None` path still fires when the
        field truly has no default. This is the case `_is_default_none`
        returns True for."""
        tool = _t("t", input_schema={
            "type": "object",
            "properties": {
                "name": {"type": "string"},
            },
            "required": [],
        })
        src, _ = translate_tool(tool, **_FIXED_HEADER_KW)
        params_section = src.split("class TResponse")[0]
        # No default in schema, not required -> nullable scalar.
        assert "name: str | None = Field(default=None" in params_section
