"""Unit tests for mcp_test_framework.test_code._codegen smoke-scenario emission.

Pins (Phase 999.2 -- GEN-03, GEN-04, GEN-05):
  - examples-present (single) -> real scenario w/ CreateVmParams(**{...}) and
    await tool("<name>").call(params)
  - examples-present (multi)  -> @pytest.mark.parametrize with positional
    example-{i} ids (Pitfall 4 -- stable parametrize IDs across operator edits)
  - examples absent/empty     -> pytest.skip(allow_module_level=True) with
    the EXACT grep-able reason text from D-02a; relative import still present
    (D-02 -- module fully importable)
  - 4-line header sentinel shared with <tool>.py via _render_header()
  - relative import `from .<mod> import <Pascal>Params` (Pitfall 2 guard)
  - @pytest.mark.asyncio(loop_scope="session") literal (Pitfall 1 guard)
  - operator-supplied example values json.dumps()-escaped
    (V5 input validation / Tampering mitigation; mirrors _codegen.py:582-590)
"""
from __future__ import annotations

import pytest
from mcp.types import Tool

from mcp_test_framework.test_code._codegen import _emit_smoke_scenario, generate


_FIXED_TS = "2026-05-12T14:23:01+00:00"


def _t(name: str, *, input_schema: dict | None = None, output_schema: dict | None = None) -> Tool:
    return Tool(
        name=name,
        description=f"Test tool {name}",
        inputSchema=(
            input_schema
            if input_schema is not None
            else {"type": "object", "properties": {}, "required": []}
        ),
        outputSchema=output_schema,
    )


def _required_tool(name: str = "create_vm") -> Tool:
    return _t(name, input_schema={
        "type": "object",
        "properties": {
            "vmid": {"type": "integer"},
            "name": {"type": "string"},
        },
        "required": ["vmid", "name"],
    })


class _ToolCfgShim:
    """Duck-typed stand-in for ToolConfig — only needs .examples for the generate() loop.

    Mirrors the shim added in plan 03 to tests/framework/unit/test_codegen_emitter.py.
    Duplicated here so each test file is self-contained (no shared fixture, no conftest
    coupling).
    """
    def __init__(self, examples=None):
        self.examples = examples


def test_emit_smoke_returns_string_with_header_sentinel() -> None:
    """Single-example branch returns a string with the 4-line header sentinel."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert isinstance(src, str)
    assert "# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT." in src
    assert f"# Regenerated: {_FIXED_TS}" in src


def test_emit_smoke_uses_relative_import() -> None:
    """Single-example for tool 'create_vm' -> contains `from .create_vm import CreateVmParams`."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert "from .create_vm import CreateVmParams" in src


def test_emit_smoke_uses_loop_scope_session_marker() -> None:
    """Single-example -> contains `@pytest.mark.asyncio(loop_scope="session")` (Pitfall 1 guard)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert '@pytest.mark.asyncio(loop_scope="session")' in src


def test_emit_smoke_single_example_constructs_params_directly() -> None:
    """Single-example -> contains CreateVmParams(**{ and the values; no _EXAMPLES = [."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert "CreateVmParams(**{" in src
    assert "9001" in src
    assert "smoke" in src
    assert "_EXAMPLES = [" not in src


def test_emit_smoke_single_example_awaits_tool_call() -> None:
    """Single-example -> contains `await tool("create_vm").call(params)`."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert 'await tool("create_vm").call(params)' in src


def test_emit_smoke_multi_example_uses_parametrize() -> None:
    """Multi-example -> _EXAMPLES, @pytest.mark.parametrize with example-{i} ids, and correct signature."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001}, {"vmid": 9002}],
    )
    assert "_EXAMPLES = [" in src
    assert '@pytest.mark.parametrize("example", _EXAMPLES, ids=[f"example-{i}" for i in range(len(_EXAMPLES))])' in src
    assert "params = CreateVmParams(**example)" in src
    assert "async def test_create_vm_call_smoke(mcp_session, example):" in src


def test_emit_smoke_todo_branch_when_examples_none() -> None:
    """examples=None -> pytest.skip with exact D-02a reason, relative import, # noqa: F401, no loop_scope."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=None,
    )
    assert "pytest.skip(" in src
    assert '"no examples; populate tools.create_vm.examples: in config.yaml to enable this smoke"' in src
    assert "allow_module_level=True," in src
    assert "from .create_vm import CreateVmParams" in src
    assert "# noqa: F401" in src
    assert 'loop_scope' not in src


def test_emit_smoke_todo_branch_when_examples_empty_list() -> None:
    """examples=[] -> same TODO behavior as examples=None (empty == absent)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[],
    )
    assert "pytest.skip(" in src
    assert '"no examples; populate tools.create_vm.examples: in config.yaml to enable this smoke"' in src
    assert "allow_module_level=True," in src
    assert "from .create_vm import CreateVmParams" in src
    assert "# noqa: F401" in src


def test_emit_smoke_todo_branch_import_precedes_skip() -> None:
    """examples=None -> relative import appears BEFORE pytest.skip() (D-02 + research Q6)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=None,
    )
    import_pos = src.index("from .create_vm import CreateVmParams")
    skip_pos = src.index("pytest.skip(")
    assert import_pos < skip_pos, (
        "Relative import must appear BEFORE pytest.skip() so an ImportError "
        "surfaces as a real codegen bug rather than being masked by the skip."
    )


def test_emit_smoke_example_values_json_escaped() -> None:
    """Operator values with quotes/newlines are json.dumps()-escaped so they cannot inject source."""
    dangerous_value = 'vm-with-"quote"-and-\nnewline'
    import json
    safe_repr = json.dumps(dangerous_value)  # '"vm-with-\\"quote\\"-and-\\nnewline"'
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"name": dangerous_value}],
    )
    # The safe escaped form must appear in the source
    assert safe_repr in src
    # The raw unescaped value must NOT appear (would close the dict literal early)
    assert dangerous_value not in src


# ------------------------------------------------------------------
# Plan 04: end-to-end integration tests (GEN-07)
# ------------------------------------------------------------------


def test_smoke_file_header_sentinel_matches_existing_tool_py_style(tmp_path) -> None:
    """D-03a: a single grep across _generated/ finds both kinds of generated files.

    Both <tool>.py and <tool>_call_smoke.py MUST start with the same header sentinel
    produced by _render_header(), so the operator's regen/cleanup grep finds both.
    """
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}},
        "required": ["vmid"],
    })
    tools_cfg = {"create_vm": _ToolCfgShim(examples=[{"vmid": 9001}])}
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    tool_py = (tmp_path / "homelab_mcp" / "create_vm.py").read_text(encoding="utf-8")
    smoke_py = (tmp_path / "homelab_mcp" / "create_vm_call_smoke.py").read_text(encoding="utf-8")
    sentinel = "# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT."
    assert tool_py.startswith(sentinel), "<tool>.py header sentinel regressed"
    assert smoke_py.startswith(sentinel), "<tool>_call_smoke.py header sentinel regressed"


def test_smoke_file_overwritten_unconditionally(tmp_path) -> None:
    """D-03: unconditional overwrite. Operator edits to <tool>_call_smoke.py are wiped on regen.

    Mechanism: generate() calls shutil.rmtree(target, ignore_errors=True) at line 643
    before re-writing. Smoke files live inside `target`, so they participate in the wipe.
    """
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}},
        "required": ["vmid"],
    })
    tools_cfg = {"create_vm": _ToolCfgShim(examples=[{"vmid": 9001}])}
    kwargs = dict(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    generate(**kwargs)
    smoke_path = tmp_path / "homelab_mcp" / "create_vm_call_smoke.py"
    original = smoke_path.read_text(encoding="utf-8")

    # Operator edit (simulated)
    smoke_path.write_text("# operator-edited content\n", encoding="utf-8")

    # Regen with identical inputs (fixed timestamp -> byte-identical original output)
    generate(**kwargs)
    regenerated = smoke_path.read_text(encoding="utf-8")
    assert regenerated == original, "operator edit survived regen — D-03 unconditional overwrite broken"
    assert "operator-edited content" not in regenerated


def test_smoke_file_init_py_unchanged(tmp_path) -> None:
    """Smoke modules are pytest test modules, NOT Params/Response carriers.

    They MUST NOT appear in _REGISTRY or in the package's `from .<mod> import ...` lines
    in __init__.py. Pin this against future codegen changes.
    """
    tools = [
        _t("create_vm", input_schema={
            "type": "object",
            "properties": {"vmid": {"type": "integer"}},
            "required": ["vmid"],
        }),
        _t("ping"),  # required: []  -> no smoke file
    ]
    tools_cfg = {"create_vm": _ToolCfgShim(examples=[{"vmid": 9001}])}
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    init = (tmp_path / "homelab_mcp" / "__init__.py").read_text(encoding="utf-8")
    # Smoke modules MUST NOT be imported into the package
    assert "create_vm_call_smoke" not in init, (
        "__init__.py imported a smoke module -- smoke files are pytest test modules, "
        "not Params/Response carriers; they MUST NOT appear in _REGISTRY or the "
        "package's import list."
    )
    # Sanity: the real per-tool module IS imported
    assert "from .create_vm import" in init


def test_todo_branch_module_is_importable(tmp_path) -> None:
    """D-02: TODO/skip module MUST be fully importable (no NameError on Params).

    The generated module must parse as valid Python source. We check via compile() rather
    than actually exec'ing (exec'ing would trigger pytest.skip(allow_module_level=True)
    which raises a Skipped exception outside a pytest collection context).
    """
    t = _t("create_vm", input_schema={
        "type": "object",
        "properties": {"vmid": {"type": "integer"}},
        "required": ["vmid"],
    })
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=[t], out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=None,  # no examples -> TODO branch
    )
    smoke_path = tmp_path / "homelab_mcp" / "create_vm_call_smoke.py"
    src = smoke_path.read_text(encoding="utf-8")
    # Parse + compile to bytecode -- raises SyntaxError if the emitter produced bad Python
    compiled = compile(src, str(smoke_path), "exec")
    assert compiled is not None
    # Confirm the operator-readable signal is present in the source body
    assert "from .create_vm import CreateVmParams" in src
    assert "pytest.skip(" in src
    assert "allow_module_level=True" in src


def test_generate_multi_tool_mixed_branches(tmp_path) -> None:
    """End-to-end: one generate() call producing three different per-tool branches.

    Pins that the per-tool loop correctly routes each tool to the right branch based
    on (required-field?, examples?) — no cross-tool leakage.
    """
    tools = [
        # (a) required + examples -> real scenario
        _t("create_vm", input_schema={
            "type": "object",
            "properties": {"vmid": {"type": "integer"}, "name": {"type": "string"}},
            "required": ["vmid", "name"],
        }),
        # (b) required + no examples -> TODO branch
        _t("delete_vm", input_schema={
            "type": "object",
            "properties": {"vmid": {"type": "integer"}},
            "required": ["vmid"],
        }),
        # (c) no required -> NO smoke file
        _t("list_vms"),
    ]
    tools_cfg = {
        "create_vm": _ToolCfgShim(examples=[{"vmid": 9001, "name": "smoke"}]),
        # "delete_vm" deliberately absent — exercises the TODO branch
    }
    generate(
        server_name="homelab-mcp", server_version="0.5.2",
        tools=tools, out_root=tmp_path, timestamp=_FIXED_TS,
        tools_config=tools_cfg,
    )
    out = tmp_path / "homelab_mcp"

    # (a) create_vm -> real scenario
    create_smoke = (out / "create_vm_call_smoke.py").read_text(encoding="utf-8")
    assert "@pytest.mark.asyncio(loop_scope=\"session\")" in create_smoke
    assert "pytest.skip" not in create_smoke
    assert "await tool(\"create_vm\").call(params)" in create_smoke

    # (b) delete_vm -> TODO branch
    delete_smoke = (out / "delete_vm_call_smoke.py").read_text(encoding="utf-8")
    assert "pytest.skip(" in delete_smoke
    assert "populate tools.delete_vm.examples: in config.yaml to enable this smoke" in delete_smoke
    assert "from .delete_vm import DeleteVmParams" in delete_smoke

    # (c) list_vms -> no smoke file at all
    assert not (out / "list_vms_call_smoke.py").exists()
    assert (out / "list_vms.py").exists()
