"""Unit tests for mcp_test_framework.test_code._codegen smoke-scenario emission.

Pins (Phase 999.2 -- GEN-03, GEN-04, GEN-05):
  - examples-present (single) -> real scenario w/ CreateVmParams(**{...}) and
    await tool("<name>").call(params)
  - examples-present (multi)  -> @pytest.mark.parametrize with positional
    example-{i} ids (Pitfall 4 -- stable parametrize IDs across operator edits)
  - examples absent/empty     -> pytest.skip(allow_module_level=True) with
    the EXACT grep-able reason text from D-02a; relative import still present
    (D-02 -- module fully importable)
  - 4-line header sentinel shared with <tool>.py via _render_header()
  - relative import `from .<mod> import <Pascal>Params` (Pitfall 2 guard)
  - @pytest.mark.asyncio(loop_scope="session") literal (Pitfall 1 guard)
  - operator-supplied example values json.dumps()-escaped
    (V5 input validation / Tampering mitigation; mirrors _codegen.py:582-590)
"""
from __future__ import annotations

import pytest
from mcp.types import Tool

from mcp_test_framework.test_code._codegen import _emit_smoke_scenario


_FIXED_TS = "2026-05-12T14:23:01+00:00"


def _t(name: str, *, input_schema: dict | None = None, output_schema: dict | None = None) -> Tool:
    return Tool(
        name=name,
        description=f"Test tool {name}",
        inputSchema=(
            input_schema
            if input_schema is not None
            else {"type": "object", "properties": {}, "required": []}
        ),
        outputSchema=output_schema,
    )


def _required_tool(name: str = "create_vm") -> Tool:
    return _t(name, input_schema={
        "type": "object",
        "properties": {
            "vmid": {"type": "integer"},
            "name": {"type": "string"},
        },
        "required": ["vmid", "name"],
    })


def test_emit_smoke_returns_string_with_header_sentinel() -> None:
    """Single-example branch returns a string with the 4-line header sentinel."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert isinstance(src, str)
    assert "# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT." in src
    assert f"# Regenerated: {_FIXED_TS}" in src


def test_emit_smoke_uses_relative_import() -> None:
    """Single-example for tool 'create_vm' -> contains `from .create_vm import CreateVmParams`."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert "from .create_vm import CreateVmParams" in src


def test_emit_smoke_uses_loop_scope_session_marker() -> None:
    """Single-example -> contains `@pytest.mark.asyncio(loop_scope="session")` (Pitfall 1 guard)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert '@pytest.mark.asyncio(loop_scope="session")' in src


def test_emit_smoke_single_example_constructs_params_directly() -> None:
    """Single-example -> contains CreateVmParams(**{ and the values; no _EXAMPLES = [."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert "CreateVmParams(**{" in src
    assert "9001" in src
    assert "smoke" in src
    assert "_EXAMPLES = [" not in src


def test_emit_smoke_single_example_awaits_tool_call() -> None:
    """Single-example -> contains `await tool("create_vm").call(params)`."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001, "name": "smoke"}],
    )
    assert 'await tool("create_vm").call(params)' in src


def test_emit_smoke_multi_example_uses_parametrize() -> None:
    """Multi-example -> _EXAMPLES, @pytest.mark.parametrize with example-{i} ids, and correct signature."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"vmid": 9001}, {"vmid": 9002}],
    )
    assert "_EXAMPLES = [" in src
    assert '@pytest.mark.parametrize("example", _EXAMPLES, ids=[f"example-{i}" for i in range(len(_EXAMPLES))])' in src
    assert "params = CreateVmParams(**example)" in src
    assert "async def test_create_vm_call_smoke(mcp_session, example):" in src


def test_emit_smoke_todo_branch_when_examples_none() -> None:
    """examples=None -> pytest.skip with exact D-02a reason, relative import, # noqa: F401, no loop_scope."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=None,
    )
    assert "pytest.skip(" in src
    assert '"no examples; populate tools.create_vm.examples: in config.yaml to enable this smoke"' in src
    assert "allow_module_level=True," in src
    assert "from .create_vm import CreateVmParams" in src
    assert "# noqa: F401" in src
    assert 'loop_scope' not in src


def test_emit_smoke_todo_branch_when_examples_empty_list() -> None:
    """examples=[] -> same TODO behavior as examples=None (empty == absent)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[],
    )
    assert "pytest.skip(" in src
    assert '"no examples; populate tools.create_vm.examples: in config.yaml to enable this smoke"' in src
    assert "allow_module_level=True," in src
    assert "from .create_vm import CreateVmParams" in src
    assert "# noqa: F401" in src


def test_emit_smoke_todo_branch_import_precedes_skip() -> None:
    """examples=None -> relative import appears BEFORE pytest.skip() (D-02 + research Q6)."""
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=None,
    )
    import_pos = src.index("from .create_vm import CreateVmParams")
    skip_pos = src.index("pytest.skip(")
    assert import_pos < skip_pos, (
        "Relative import must appear BEFORE pytest.skip() so an ImportError "
        "surfaces as a real codegen bug rather than being masked by the skip."
    )


def test_emit_smoke_example_values_json_escaped() -> None:
    """Operator values with quotes/newlines are json.dumps()-escaped so they cannot inject source."""
    dangerous_value = 'vm-with-"quote"-and-\nnewline'
    import json
    safe_repr = json.dumps(dangerous_value)  # '"vm-with-\\"quote\\"-and-\\nnewline"'
    src = _emit_smoke_scenario(
        _required_tool("create_vm"),
        slug="homelab_mcp",
        server_name="homelab-mcp",
        server_version="0.5.2",
        timestamp=_FIXED_TS,
        examples=[{"name": dangerous_value}],
    )
    # The safe escaped form must appear in the source
    assert safe_repr in src
    # The raw unescaped value must NOT appear (would close the dict literal early)
    assert dangerous_value not in src
