"""JSON-Schema -> Pydantic v2 source emission. Hand-rolled.

Coverage promise -- translates faithfully:
  - type: "string" / "integer" / "number" / "boolean" -> str / int / float / bool
  - type: "object" with properties + required -> Pydantic BaseModel
  - type: "array" with scalar items.type -> list[<scalar>]

Degradation -- everything else types to ``typing.Any`` with a
``# codegen: degraded -- <reason>`` comment directly above the field:
  - enum (any shape)              -> "enum not in v1.3 coverage"
  - oneOf                          -> "oneOf not in v1.3 coverage"
  - anyOf                          -> "anyOf not in v1.3 coverage"
  - $ref                           -> "$ref not in v1.3 coverage"
  - type: list (e.g. ["X","null"]) -> "multi-type / nullable not in v1.3 coverage"
  - array with non-scalar items    -> "array with non-scalar items not in v1.3 coverage"
  - unknown / missing type         -> "unknown type: <repr>"

Every emitted file starts with the AUTOGENERATED header. ``generate()`` wipes
``generated/<slug>/`` and writes fresh.

Pure-data: this module reads dicts and emits strings. No filesystem I/O in
``translate_tool``; ``generate`` owns ``shutil.rmtree`` + ``write_text``.
"""
from __future__ import annotations

import datetime as _dt
import json
import keyword
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from mcp.types import Tool

from mcp_test_framework.test_code._slugs import module_name, pascal_case, server_slug

# NOTE: jsonschema's `Draft202012Validator` / `validator_for` are deliberately
# NOT imported here. MCP tool schemas declare Draft 2020-12, but calling
# `check_schema(...)` (the full metaschema validator) would reject fields
# like `{"type": "color"}` outright. The walker's contract is to DEGRADE on
# unknown type tokens, not refuse. `_check_schema_structural` below catches
# structurally-broken schemas (e.g. `required: "not-a-list"`) without forcing
# every type token to be a JSON Schema primitive.


HEADER_TEMPLATE = (
    "# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.\n"
    "# Source: {slug} (serverInfo.name={server_name_repr}, version={server_version_repr})\n"
    "# Regenerated: {timestamp}\n"
    "# Extend by subclassing in tests/test_code/, not by editing this file.\n"
)


def _render_header(*, slug: str, server_name: str, server_version: str, timestamp: str) -> str:
    """Render HEADER_TEMPLATE with escaped server_name / server_version.

    serverInfo.name / version flow from the MCP `initialize` handshake -- the
    server can advertise arbitrary strings, including embedded `"` / newlines
    that would close the Python comment early and inject executable source
    into the generated file (which the test-code fixture then imports). We use
    `json.dumps(...)` to produce a safely-escaped double-quoted literal:
    embedded quotes, newlines, and unicode are all stringified into harmless
    escape sequences. The visible byte-for-byte form for safe inputs is
    unchanged (e.g. `homelab-mcp` -> `"homelab-mcp"`).
    """
    return HEADER_TEMPLATE.format(
        slug=slug,
        server_name_repr=json.dumps(server_name),
        server_version_repr=json.dumps(server_version),
        timestamp=timestamp,
    )


_SCALAR_MAP: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


@dataclass(frozen=True)
class FieldSpec:
    """A single Pydantic-model field as the walker plans it.

    py_type:        the post-`from __future__ import annotations` annotation
                    string (e.g. "str", "list[int]", "typing.Any").
    default_expr:   the right-hand side of `<name>: <py_type> = <default_expr>`.
                    For required fields this is `Field(...)`. For optional with
                    a default it is `Field(default=<repr>)`. For optional
                    without a default it is `Field(default=None)` and the type
                    becomes `<py_type> | None` (only at the top scalar level --
                    we don't degrade-then-nullable in v1.3).
    degrade_reason: human-readable phrase if this field is a degradation,
                    else None. Emitted as `# codegen: degraded -- <reason>`
                    on the line above the field.
    default_is_none: True iff this field has no required-status AND no schema
                    default (so `_default_expr` produced `Field(default=None)`).
                    Structured signal consumed by `_format_field_line` to add
                    `| None` to the type annotation; avoids a substring scan
                    of `default_expr` for "default=None", which would
                    false-positive on any field whose description contained
                    the literal "default=None".
    """
    py_type: str
    default_expr: str
    degrade_reason: str | None
    default_is_none: bool = False


class SchemaValidityError(ValueError):
    """Raised when an MCP tool's inputSchema is not a valid JSON Schema document.

    The codegen refuses to translate an invalid schema (loud-fail); the CLI
    command maps this to an operator error naming the offending tool.
    """


def _check_schema_structural(tool_name: str, schema: dict) -> None:
    """Structural sanity check for a tool's inputSchema.

    MCP tool schemas are Draft 2020-12. We deliberately do NOT call
    `Draft202012Validator.check_schema(schema)` because the full metaschema
    rejects fields like `{"type":"color"}` -- and the walker's contract is to
    DEGRADE on unknown type tokens, not refuse the whole tool.

    This check catches the narrow class of malformed schemas the walker
    cannot operate on:
      - root `type:"object"` with `required` that is not a list
      - root `properties` that is not a dict (when present)

    Other shape weirdness (unknown type tokens, nested-object recursion,
    oneOf/anyOf/$ref combinators) falls through to `_emit_field` which
    degrades cleanly.
    """
    if not isinstance(schema, dict):
        return  # nothing to check; caller already coerced non-dicts away
    required = schema.get("required")
    if required is not None and not isinstance(required, list):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'required' must be a list, got "
            f"{type(required).__name__}). Refusing to translate."
        )
    props = schema.get("properties")
    if props is not None and not isinstance(props, dict):
        raise SchemaValidityError(
            f"tool {tool_name!r}: inputSchema is not a valid JSON Schema "
            f"document (SchemaError: 'properties' must be an object, got "
            f"{type(props).__name__}). Refusing to translate."
        )


def _is_default_none(schema: dict, required: bool) -> bool:
    """True iff `_default_expr(schema, required)` emits `Field(default=None...)`.

    Structured signal used by `_format_field_line` to decide whether to add
    `| None` to the type. Avoids substring-matching `"default=None"` in
    `spec.default_expr`, which would false-positive when a field's
    description literally contained the string `default=None`.
    """
    return (not required) and ("default" not in schema)


def _default_expr(schema: dict, required: bool) -> str:
    """Build the `Field(...)` right-hand side for a single field.

    Required fields get `Field(...)` (Ellipsis). Optional fields with a
    declared default get `Field(default=<repr>)`. Optional fields without
    a default get `Field(default=None)` -- and the type gets a `| None`
    union applied at emit-site (handled in `_format_field_line`) via the
    structured `FieldSpec.default_is_none` flag (NOT a substring scan --
    see `_is_default_none`).

    description is lifted from schema["description"] if present; quoted via
    repr() for safe escaping.
    """
    desc = schema.get("description")
    desc_kwarg = f", description={desc!r}" if isinstance(desc, str) and desc else ""
    if required:
        return f"Field(...{desc_kwarg})"
    if "default" in schema:
        return f"Field(default={schema['default']!r}{desc_kwarg})"
    return f"Field(default=None{desc_kwarg})"


def _emit_field(schema: dict, *, required: bool) -> FieldSpec:
    """Translate one property's schema to a FieldSpec.

    `name` is owned by `_format_field_line`, which receives it separately
    (this function operates only on the schema for one property and whether
    it is required).

    Order of checks matters: degradation triggers (enum/oneOf/anyOf/$ref/
    multi-type) take precedence over `type:` dispatch so that
    `{"type":"string","enum":["a","b"]}` degrades to Any (not str).

    `default_is_none` is computed ONCE here via `_is_default_none` and
    threaded through every `FieldSpec(...)` construction (avoids substring-
    scanning `default_expr` for "default=None", which false-positives on
    descriptions containing that literal).
    """
    is_none = _is_default_none(schema, required)
    # Degradation triggers -- check FIRST.
    if "enum" in schema:
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "enum not in v1.3 coverage",
            default_is_none=is_none,
        )
    for combinator in ("oneOf", "anyOf", "$ref"):
        if combinator in schema:
            return FieldSpec(
                "typing.Any", _default_expr(schema, required),
                f"{combinator} not in v1.3 coverage",
                default_is_none=is_none,
            )
    jtype = schema.get("type")
    if isinstance(jtype, list):
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "multi-type / nullable not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Faithful translation paths.
    if isinstance(jtype, str) and jtype in _SCALAR_MAP:
        return FieldSpec(
            _SCALAR_MAP[jtype], _default_expr(schema, required), None,
            default_is_none=is_none,
        )
    if jtype == "array":
        items = schema.get("items") or {}
        items_type = items.get("type")
        if isinstance(items_type, str) and items_type in _SCALAR_MAP:
            return FieldSpec(
                f"list[{_SCALAR_MAP[items_type]}]",
                _default_expr(schema, required),
                None,
                default_is_none=is_none,
            )
        return FieldSpec(
            "typing.Any", _default_expr(schema, required),
            "array with non-scalar items not in v1.3 coverage",
            default_is_none=is_none,
        )
    if jtype == "object":
        # Nested objects in v1.3: degrade to dict[str, Any]; full nested-model
        # emission is a v1.4 expansion. The current goal is the walker + the
        # seam, not deep type fidelity (narrow coverage promise).
        return FieldSpec(
            "dict[str, typing.Any]", _default_expr(schema, required),
            None if "properties" not in schema else
            "nested-object recursion not in v1.3 coverage",
            default_is_none=is_none,
        )

    # Unknown / missing type.
    return FieldSpec(
        "typing.Any", _default_expr(schema, required),
        f"unknown type: {jtype!r}",
        default_is_none=is_none,
    )


_FIELD_NON_IDENT = re.compile(r"[^a-zA-Z0-9_]+")


def _safe_field_ident(name: str) -> tuple[str, str | None]:
    """Map a JSON-Schema property name to (python_ident, alias_if_renamed).

    JSON-Schema property keys are arbitrary strings -- Python keywords
    (`class`, `import`), leading-digit (`2fa_code`), hyphenated (`vm-id`),
    whitespace / unicode (`vm id`, `配置`) all produce SyntaxError when
    interpolated verbatim into `<name>: <type> = Field(...)`. The slug and
    PascalCase helpers in `_slugs.py` already implement this guard for module
    and class names; the field path needs an equivalent.

    Returns (ident, alias):
      - ident: the safe Python identifier to emit on the LHS of the field
        declaration.
      - alias: the original (wire) name, or None when no rename was needed.
        Callers thread alias through `Field(alias=<original>)` so Pydantic
        validates the wire field under its real name even though the Python
        attribute has been renamed.

    Sanitization strategy is close to `module_name` in `_slugs.py` but
    diverges on the leading-digit case: Pydantic v2 raises NameError on
    any field whose Python attribute name starts with "_" (interpreted as a
    private attr). So leading-digit / collapsed-to-empty names are prefixed
    with "f_" instead of "_", keeping the attribute public.

    Rules:
      - non-ident chars -> "_"
      - strip leading/trailing "_"
      - leading-digit / empty -> prefix "f_"
      - keyword -> suffix "_"
    """
    if name.isidentifier() and not keyword.iskeyword(name):
        return name, None
    ident = _FIELD_NON_IDENT.sub("_", name).strip("_")
    if not ident:
        # All-non-ident input (e.g. "---" or unicode-only) collapses to empty.
        ident = "f_field"
    elif ident[0].isdigit():
        # Pydantic rejects leading-underscore field names (NameError at class
        # construction), so use "f_" rather than the "_" prefix used by
        # `module_name` for module file names.
        ident = "f_" + ident
    if keyword.iskeyword(ident):
        ident = ident + "_"
    return ident, name


def _inject_alias(default_expr: str, alias: str) -> str:
    """Insert `alias=<repr(alias)>` as the first keyword argument inside Field(...).

    `default_expr` is always one of:
      - `Field(...)`                                    (required)
      - `Field(...,  description='...')`                (required + desc)
      - `Field(default=<repr>)`                         (optional with default)
      - `Field(default=<repr>, description='...')`      (optional with default + desc)
      - `Field(default=None)`                           (optional, no default)
      - `Field(default=None, description='...')`        (optional, no default + desc)

    All shapes start with literal `Field(` and end with `)`. We splice
    `alias=<repr>, ` immediately after the opening paren so it lands as the
    first keyword. The repr is via `json.dumps` for a safely-escaped
    double-quoted Python string literal.
    """
    assert default_expr.startswith("Field("), (
        f"_inject_alias: unexpected default_expr shape: {default_expr!r}"
    )
    head = "Field("
    rest = default_expr[len(head):]
    # `Field(...)` -- positional `...` is the required marker; alias goes AFTER
    # it as a kwarg, not before. Detect and splice after.
    if rest.startswith("..."):
        after_ellipsis = rest[3:]
        if after_ellipsis.startswith(", "):
            return f"Field(..., alias={json.dumps(alias)},{after_ellipsis[1:]}"
        if after_ellipsis.startswith(")"):
            return f"Field(..., alias={json.dumps(alias)}){after_ellipsis[1:]}"
        # Defensive fallback for any unexpected shape.
        return f"Field(..., alias={json.dumps(alias)}, {after_ellipsis}"
    # Kwarg-only forms: splice alias= as the first kwarg.
    return f"Field(alias={json.dumps(alias)}, {rest}"


def _format_field_line(name: str, spec: FieldSpec, *, required: bool) -> str:
    """Render a FieldSpec to source lines (degrade comment + field decl).

    Uses the structured `FieldSpec.default_is_none` flag (set by
    `_emit_field`) rather than substring-matching `"default=None"` in
    `spec.default_expr`, which would false-positive when a description
    happened to contain that literal string.

    `name` is the JSON-Schema property key (the wire-side name);
    `_safe_field_ident` maps it to a valid Python identifier, and any
    rename injects `alias=<original>` into the `Field(...)` call so Pydantic
    still validates the wire field under its real name.
    """
    py_type = spec.py_type
    # Optional fields without an explicit default get `| None`. Skip when the
    # type is already `typing.Any` (Any subsumes None). Note: the original
    # predicate also required `degrade_reason is None` -- that excluded
    # nested-object degradation paths that still emit a concrete
    # `dict[str, typing.Any]` type (not Any), so pyright rejected
    # `config: dict[str, Any] = Field(default=None)`. Any field with
    # `default_is_none` and a non-Any type needs `| None` regardless of
    # degrade status.
    if not required and spec.default_is_none and py_type != "typing.Any":
        py_type = f"{py_type} | None"
    # Sanitize the LHS identifier and inject `alias=` on rename.
    ident, alias = _safe_field_ident(name)
    default_expr = spec.default_expr
    if alias is not None:
        default_expr = _inject_alias(default_expr, alias)
    lines: list[str] = []
    if spec.degrade_reason is not None:
        lines.append(f"    # codegen: degraded -- {spec.degrade_reason}")
    lines.append(f"    {ident}: {py_type} = {default_expr}")
    return "\n".join(lines)


@dataclass(frozen=True)
class _BodyEmission:
    """Structured output of `_emit_params_body` / `_emit_response_body`.

    Replaces a prior `(body_text, degraded_count)` tuple plus post-render
    substring scans on the rendered text. The substring scan false-positived
    when a field description literally contained "typing." or "Field(" -- a
    description like "Accepts any typing.Any-compatible value" caused the
    emitter to write `import typing` against a body that never referenced
    typing.Any, resurrecting an orphaned-import shape pyright-strict's
    `reportUnusedImport` rejects.

    Fields:
      body_text:        the rendered class body (with the trailing newline
                        the previous return shape already included).
      degraded_count:   how many fields fell to a typing.Any (or
                        dict[str, typing.Any]) degradation path.
      uses_typing_any:  True iff ANY emitted field's annotation references
                        `typing.` (covers both bare `typing.Any` and
                        composite `dict[str, typing.Any]`). Structured
                        signal -- consulted at the import-emission site
                        instead of substring-scanning the rendered body.
      has_fields:       True iff at least one `Field(...)` call was
                        emitted. False for `pass`-body classes (no
                        properties, non-object inputSchema, or None
                        outputSchema). Structured signal for the
                        conditional `from pydantic import ..., Field`.
    """
    body_text: str
    degraded_count: int
    uses_typing_any: bool
    has_fields: bool


def _emit_params_body(schema: dict | None) -> _BodyEmission:
    """Emit the body of a <Tool>Params class.

    Empty / non-object inputSchema -> `pass` body. degraded_count is 0 in
    that case and both `uses_typing_any` / `has_fields` are False.
    """
    if not isinstance(schema, dict) or schema.get("type") != "object":
        return _BodyEmission("    pass\n", 0, False, False)
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    if not props:
        return _BodyEmission("    pass\n", 0, False, False)
    degraded = 0
    uses_typing_any = False
    lines: list[str] = []
    # Required first (alphabetical), then optional (alphabetical) -- matches
    # the ordering convention used by `_format_param_signature` in cli.py.
    req_names = sorted(n for n in props if n in required)
    opt_names = sorted(n for n in props if n not in required)
    for name in req_names + opt_names:
        prop_schema = props[name] if isinstance(props[name], dict) else {}
        spec = _emit_field(prop_schema, required=(name in required))
        if spec.degrade_reason is not None:
            degraded += 1
        if "typing." in spec.py_type:
            uses_typing_any = True
        lines.append(_format_field_line(name, spec, required=(name in required)))
    # `lines` is non-empty here because `props` is non-empty and we iterate
    # over both required and optional names. `has_fields=True`.
    return _BodyEmission(
        body_text="\n".join(lines) + "\n",
        degraded_count=degraded,
        uses_typing_any=uses_typing_any,
        has_fields=True,
    )


def _emit_response_body(schema: dict | None) -> _BodyEmission:
    """Emit the body of a <Tool>Response class. Stub-body when schema is None."""
    if schema is None:
        return _BodyEmission("    pass\n", 0, False, False)
    # When outputSchema IS declared, treat it the same as Params (object walk).
    return _emit_params_body(schema)


def translate_tool(
    tool: Tool,
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
) -> tuple[str, int]:
    """Translate one MCP Tool to a per-tool source file (str). Pure-data.

    Returns (source_text, degraded_field_count).

    Refuses to translate if `tool.inputSchema` is not a valid JSON Schema
    document (raises SchemaValidityError).
    """
    input_schema = tool.inputSchema if isinstance(tool.inputSchema, dict) else {}
    # Always run the structural check on dict inputs (the function short-
    # circuits on non-dict). An `if input_schema:` guard would let a schema
    # like `{"required": "not-a-list"}` slip through -- it has no `type` /
    # `properties` so `_emit_params_body` falls to the `pass` body path,
    # silently accepting a schema the structural check would otherwise
    # refuse. Calling unconditionally aligns the gating with the function's
    # documented contract.
    _check_schema_structural(tool.name, input_schema)

    cls_base = pascal_case(tool.name)
    header = _render_header(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )

    params = _emit_params_body(input_schema)
    output_schema = tool.outputSchema if isinstance(tool.outputSchema, dict) else None
    response = _emit_response_body(output_schema)

    response_class = (
        f"class {cls_base}Response(ToolResponse):\n"
        f'    """Typed response for the `{tool.name}` tool.\n\n'
        f"    Inherits .raw / .data / .text / .is_error from ToolResponse.\n"
    )
    if output_schema is None:
        # Stub class -- pass body, document the lack of outputSchema.
        response_class += (
            f"    outputSchema was undeclared at codegen time; .data falls\n"
            f"    back to JSON-parse / text-dict via the locked fallback chain.\n"
            f'    """\n'
            f"{response.body_text}"
        )
    else:
        response_class += f'    """\n{response.body_text}'

    # Emit `import typing` / `Field` only when the body actually uses them.
    # A substring check over the rendered body (`"typing." in body_text`,
    # `"Field(" in body_text`) would false-positive when a field's
    # description literally contained "typing." or "Field(", resurrecting an
    # orphaned-import shape pyright-strict's `reportUnusedImport` rejects.
    # `_BodyEmission` threads `uses_typing_any` / `has_fields` as structured
    # signals computed at field-emission time (over the typed FieldSpec, not
    # the rendered string), so descriptions can't poison the decision.
    needs_typing = params.uses_typing_any or response.uses_typing_any
    needs_field = params.has_fields or response.has_fields

    pydantic_imports = "BaseModel, ConfigDict"
    if needs_field:
        pydantic_imports += ", Field"
    typing_import_line = "import typing\n\n" if needs_typing else ""

    source = (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"{typing_import_line}"
        f"from pydantic import {pydantic_imports}\n\n"
        f"from mcp_test_framework.test_code.response import ToolResponse\n\n\n"
        f"class {cls_base}Params(BaseModel):\n"
        f'    """Params for the `{tool.name}` tool.\n\n'
        f"    Generated from inputSchema. Pydantic validates required / type /\n"
        f"    default rules at construction time before the wire call.\n"
        f'    """\n'
        f"    model_config = ConfigDict(extra=\"forbid\")\n\n"
        f"{params.body_text}\n\n"
        f"{response_class}"
    )
    return source, params.degraded_count + response.degraded_count


# --- File emission (wipe-and-write) ---------------------------------------
# Imports for this section (datetime, shutil, Path, server_slug) are hoisted
# to the top of the module per PEP 8; nothing to import here.


def _render_init(
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
    registry_entries: list[tuple[str, str]],  # [(tool_name, pascal_base), ...]
) -> str:
    """Render generated/<slug>/__init__.py: header + per-tool imports + _REGISTRY.

    Imports and registry entries are emitted in sorted order (diff-stable).
    """
    header = _render_header(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
    )
    # Imports, sorted alphabetically by tool_name (diff-stable).
    import_lines: list[str] = []
    all_names: list[str] = []
    registry_lines: list[str] = []
    for tool_name, pascal in sorted(registry_entries, key=lambda t: t[0]):
        params_cls = f"{pascal}Params"
        response_cls = f"{pascal}Response"
        mod = module_name(tool_name)
        import_lines.append(f"from .{mod} import {params_cls}, {response_cls}")
        all_names.extend([f'"{params_cls}"', f'"{response_cls}"'])
        # json.dumps()-escape tool_name so a server-advertised name
        # containing `"` / newline cannot close the dict-key string literal
        # and inject a callable into the registry dict (which the tool()
        # factory then dispatches against). For names that match the MCP
        # spec regex `[A-Za-z_][A-Za-z0-9_]*` the visible form is identical
        # to a bare `f'"{tool_name}"'` interpolation.
        registry_lines.append(
            f"    {json.dumps(tool_name)}: ({params_cls}, {response_cls}),"
        )

    all_block = "__all__ = [\n    " + ",\n    ".join(all_names) + ",\n]" if all_names else "__all__ = []"
    # Emit the tighter `type[BaseModel]` annotation to match
    # `_tool_factory._REGISTRIES` expectations. Downstream consumers of the
    # generated `_REGISTRY` see a typed Pydantic model class, not bare `type`.
    registry_block = (
        "# The tool(name) factory in mcp_test_framework.test_code._tool_factory\n"
        "# dispatches against this _REGISTRY.\n"
        "_REGISTRY: dict[str, tuple[type[BaseModel], type[ToolResponse]]] = {\n"
        + "\n".join(registry_lines) + "\n}\n"
    ) if registry_lines else (
        "_REGISTRY: dict[str, tuple[type[BaseModel], type[ToolResponse]]] = {}\n"
    )

    body = "\n".join(import_lines) + ("\n\n" if import_lines else "")
    return (
        f"{header}"
        f"from __future__ import annotations\n\n"
        f"from pydantic import BaseModel\n\n"
        f"from mcp_test_framework.test_code.response import ToolResponse\n\n"
        f"{body}"
        f"{all_block}\n\n"
        f"{registry_block}"
    )


def generate(
    *,
    server_name: str,
    server_version: str,
    tools: list[Tool],
    out_root: Path,
    timestamp: str | None = None,
    tools_config: "dict[str, object] | None" = None,
) -> dict[str, int]:
    """Wipe-and-write generated/<slug>/ from a list of Tool objects.

    Steps: `shutil.rmtree(target, ignore_errors=True)` -> `mkdir` -> write
    per-tool files -> write `__init__.py` LAST so partial states fail clean,
    not half-imported.

    `timestamp=None` uses `datetime.now(UTC)` at sub-second precision; tests
    pass a fixed value for byte-identical idempotency.

    Optional `tools_config` is a `{tool_name: ToolConfig}` mapping (duck-typed
    here as `dict[str, object]` to avoid importing `models.ToolConfig` from
    this pure-data module). When provided, each entry's `examples` attribute
    drives the `<tool>_call_smoke.py` scenario emission for required-field
    tools. When omitted or when a tool has no entry, required-field tools
    still get a `<tool>_call_smoke.py` -- the TODO/skip branch -- so the
    operator sees scaffolding immediately.

    Returns counts: {"tools": <N>, "degraded_fields": <M>}.
    """
    if timestamp is None:
        timestamp = _dt.datetime.now(_dt.UTC).isoformat(timespec="seconds")

    slug = server_slug(server_name)  # raises ValueError on empty/all-non-ident
    target = out_root / slug

    # Wipe.
    shutil.rmtree(target, ignore_errors=True)
    target.mkdir(parents=True, exist_ok=True)

    counts = {"tools": 0, "degraded_fields": 0}
    registry_entries: list[tuple[str, str]] = []

    # Sorted emission for diff-stability.
    for tool in sorted(tools, key=lambda t: t.name):
        rendered, degraded_n = translate_tool(
            tool, slug=slug, server_name=server_name,
            server_version=server_version, timestamp=timestamp,
        )
        per_tool_path = target / f"{module_name(tool.name)}.py"
        per_tool_path.write_text(rendered, encoding="utf-8")
        counts["tools"] += 1
        counts["degraded_fields"] += degraded_n
        registry_entries.append((tool.name, pascal_case(tool.name)))

        # Phase 999.2 / GEN-02: emit <tool>_call_smoke.py for required-field tools.
        # Gate on len(inputSchema.required) > 0 -- tools with required:[] or no
        # `required` key get NO smoke file (zero-output for clarity).
        required = tool.inputSchema.get("required") if isinstance(tool.inputSchema, dict) else None
        if isinstance(required, list) and len(required) > 0:
            tool_cfg = (tools_config or {}).get(tool.name)
            # Duck-typed read: tool_cfg is a ToolConfig but we do not import it
            # here. `examples` is the field added in plan 01 (default None).
            examples = getattr(tool_cfg, "examples", None) if tool_cfg is not None else None
            smoke_source = _emit_smoke_scenario(
                tool,
                slug=slug,
                server_name=server_name,
                server_version=server_version,
                timestamp=timestamp,
                examples=examples,
            )
            smoke_path = target / f"{module_name(tool.name)}_call_smoke.py"
            smoke_path.write_text(smoke_source, encoding="utf-8")

    # Write __init__.py LAST so partial states fail clean, not half-imported.
    init_text = _render_init(
        slug=slug, server_name=server_name,
        server_version=server_version, timestamp=timestamp,
        registry_entries=registry_entries,
    )
    (target / "__init__.py").write_text(init_text, encoding="utf-8")

    return counts


def _emit_smoke_scenario(
    tool: Tool,
    *,
    slug: str,
    server_name: str,
    server_version: str,
    timestamp: str,
    examples: list[dict[str, object]] | None,
) -> str:
    """Render the source for tests/test_code/_generated/<slug>/<tool>_call_smoke.py.

    Pure-data: returns a string. File I/O is owned by ``generate()``.

    Three branches:
      - examples is None or [] -> TODO/skip module. Module is
        fully importable; pytest.skip(allow_module_level=True) appears AFTER
        the ``from .<tool> import <Pascal>Params`` import so an ImportError
        would surface as a real codegen bug rather than being masked.
      - len(examples) == 1     -> single ``await tool("<name>").call(params)`` body
      - len(examples) > 1      -> @pytest.mark.parametrize with positional
        ``example-{i}`` ids (stable across operator example edits)

    Operator-supplied ``examples`` values are serialized via json.dumps() so
    embedded ``"`` / newline cannot close the dict literal early and inject
    executable source. Mirrors the tool-name escaping in registry_lines and
    the header escaping for server_name / server_version. Generated scenario
    is fixture-loaded via the mcp_session synthetic-package loader, which
    requires the relative ``from .<mod> import ...`` shape.

    The 4-line header sentinel is shared with <tool>.py via _render_header
    so a single grep across _generated/ finds both kinds of generated files.

    This emitter does NOT read or warn about skip_buckets.
    Examples-present and skip_buckets-set are independent operator surfaces.
    """
    header = _render_header(
        slug=slug,
        server_name=server_name,
        server_version=server_version,
        timestamp=timestamp,
    )
    mod = module_name(tool.name)
    params_cls = f"{pascal_case(tool.name)}Params"
    tool_name_repr = json.dumps(tool.name)

    # Common preamble (header + future + pytest + test_code public surface)
    # for ALL three branches.
    preamble = (
        f"{header}"
        "from __future__ import annotations\n"
        "\n"
        "import pytest\n"
        "\n"
        "from mcp_test_framework.test_code import mcp_session, tool  # noqa: F401\n"
        "\n"
    )

    # Branch C: TODO / skip. Import BEFORE pytest.skip so an ImportError
    # surfaces as a real codegen bug rather than being masked by the skip.
    if not examples:
        return (
            f"{preamble}"
            f"from .{mod} import {params_cls}  # noqa: F401\n"
            "\n"
            "pytest.skip(\n"
            f"    \"no examples; populate tools.{tool.name}.examples: in "
            "config.yaml to enable this smoke\",\n"
            "    allow_module_level=True,\n"
            ")\n"
        )

    # Branch A: single example -> direct CreateXParams(**{...}) call.
    if len(examples) == 1:
        example_lit = json.dumps(examples[0], indent=4)
        return (
            f"{preamble}"
            f"from .{mod} import {params_cls}\n"
            "\n"
            "\n"
            "@pytest.mark.asyncio(loop_scope=\"session\")\n"
            f"async def test_{mod}_call_smoke(mcp_session):\n"
            f"    params = {params_cls}(**{example_lit})\n"
            f"    response = await tool({tool_name_repr}).call(params)\n"
            "    assert response.is_error is False\n"
        )

    # Branch B: multi-example -> parametrize with positional example-{i} ids.
    examples_lit = json.dumps(list(examples), indent=4)
    return (
        f"{preamble}"
        f"from .{mod} import {params_cls}\n"
        "\n"
        "\n"
        f"_EXAMPLES = {examples_lit}\n"
        "\n"
        "\n"
        "@pytest.mark.asyncio(loop_scope=\"session\")\n"
        "@pytest.mark.parametrize(\"example\", _EXAMPLES, ids=[f\"example-{i}\" for i in range(len(_EXAMPLES))])\n"
        f"async def test_{mod}_call_smoke(mcp_session, example):\n"
        f"    params = {params_cls}(**example)\n"
        f"    response = await tool({tool_name_repr}).call(params)\n"
        "    assert response.is_error is False\n"
    )
